-- Whisper: an audio encoder run once, then a KV-cached cross-attention decode loop.
--
-- Two traced topologies (whisper_export.py): `encoder` takes a 30 s waveform -- the mel frontend is
-- inside the graph, so a host hands over audio and not features -- and `decoder` is one cached step,
-- called at n_tokens = #prompt for the prefill and at n_tokens = 1 for every token after it.
--
-- inputs: waveform (flat f32 array of exactly `loom.n_samples` samples, host-padded/trimmed to 30 s),
-- tokens (the prompt: the forced-decoder-ids prefix), max_new_tokens, eos_token (negative disables the
-- early stop). Returns the generated token ids, not including the prompt.
--
-- src/core/whisper_driver.cpp's transcribe() is exactly the loop below, in C++. Retiring it is R6 work
-- and is not done: its tests are fixtured on an OpenAI-format whisper-tiny, which this family does not
-- load. See BACKLOG.md P4.1.
