-- Family 3: an audio encoder, a projector, and a causal LM that reads the projector's rows as if they
-- were token embeddings (speech_lm_export.py, BACKLOG.md P4.3).
--
-- Four traced topologies. `encoder` takes a WAVEFORM -- the mel frontend and everything after it are
-- inside the graph, so a host hands over audio and not features -- and emits rows that are already the
-- LM's own width, `loom.frames_per_chunk` of them per `loom.samples_per_chunk` samples. `embed` turns
-- token ids into embeddings, `decoder` is one KV-cached step over embeddings, and `lm_head` turns its
-- hidden states into logits.
--
-- This file is the FAMILY's, not a leaf's, and the two leaves it serves share none of that encoder:
-- Qwen3-ASR's is a window-attention stack over one-second chunks of 128-bin mel feeding a linear
-- projector, and Granite Speech's is a conformer over twelve-second chunks of 160-bin features feeding
-- a Q-Former. Both publish the same two numbers, which is the only thing this driver needs to know
-- about either.
--
-- The prompt is text, then audio, then text, and it is fed to the decoder as one cached call per piece.
-- That is identical to feeding it concatenated -- attention is causal, so a call at n_past = k writes
-- cells [k, k+n) and attends over [0, k+n) -- and it is what lets the encoder's output reach the LM as
-- a backend-side tensor rather than a Lua table. Nothing here ever joins two tensors, because nothing
-- has to.
--
-- inputs: waveform (flat f32 array, host-padded with zeros to a multiple of `loom.samples_per_chunk`
-- samples, which every leaf's encoder contract requires), and three optional ones: audio_samples,
-- max_new_tokens and eos_token (negative disables the early stop).
--
-- `audio_samples` is how many samples the caller's REAL audio was, before it padded, and it is what
-- keeps the padding out of the answer entirely. The encoder is given it, so its attention never reads
-- the padding, its convolutions never mix it into a real frame and its projector never sees it in a
-- window; the prompt is then trimmed to the rows the real length produces, so the rest never reach the
-- language model either. This driver also repairs the head of the padding first: the frontend's own
-- STFT reflects the signal at its end, and a caller's zeros are not that reflection.
--
-- Omitting `audio_samples` means "the whole waveform is real", which is exactly what a caller whose
-- audio already filled its last chunk should say.
--
-- The prompt is built here, not passed in: it comes from the checkpoint's own chat template, rendered
-- at export time into the AUDIO_PREFIX/AUDIO_SUFFIX constants this driver's own ExportConstants block
-- declares. Returns the generated token ids, not including the prompt.
