// Tests loom::BpeVocab (src/core/bpe_vocab.cpp) against the small synthetic fixture generated by
// tests/fixtures/make_bpe_vocab_gguf.py -- exact hand-traced token ids for plain-ASCII cases (word fully
// reduced by merges, space-prefixed word with no merges, a contraction split, digit-by-digit number
// splitting), plus round-trip checks (decode(encode(x)) == nfc_normalize(x)) for the full-Unicode-fidelity
// cases (CJK, NFC recomposition) that don't have hand-traceable ids against this tiny fixture vocab.

#include "test_util.h"

#include "loom/loom.h"
#include "loom/core/bpe_vocab.h"
#include "loom/core/unicode.h"

#include <ggml-cpu.h>

int main() {
    ggml_backend_ptr backend(ggml_backend_cpu_init());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/bpe_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    LOOM_CHECK(model != nullptr);

    auto vocab = loom::BpeVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 260); // 256 base byte tokens + "ll","he","hell","hello"
    LOOM_CHECK(vocab->bos_id() == 0);
    LOOM_CHECK(vocab->eos_id() == 1);

    // "hello" fully reduces via the fixture's 4 merges to a single token, id 259 (256 base + 4th extra).
    {
        const auto ids = vocab->encode("hello");
        const std::vector<int32_t> expected = {259};
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == "hello");
    }

    // " world": leading space attaches to the following letter run (regex alternative 2's optional
    // prefix), but no merge rule matches any adjacent pair here -- 6 separate byte tokens, ids == byte
    // values directly (this fixture's base_tokens list is indexed by raw byte value, see the generator).
    {
        const auto ids = vocab->encode(" world");
        const std::vector<int32_t> expected = {32, 119, 111, 114, 108, 100}; // ' ','w','o','r','l','d'
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == " world");
    }

    // "don't": pretokenizes into ["don", "'t"] (the contraction alternative fires only at the apostrophe,
    // ahead of a bare letter-run match) -- 5 tokens, no merges apply.
    {
        const auto ids = vocab->encode("don't");
        const std::vector<int32_t> expected = {100, 111, 110, 39, 116}; // 'd','o','n','\'','t'
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == "don't");
    }

    // "12": \p{N} has no quantifier in the pretokenizer regex -- each digit is its own chunk, so "12"
    // never has a chance to merge into one piece even though nothing here forbids the *bytes* '1','2'
    // from being adjacent -- this is a deliberate, easy-to-get-wrong detail of the real Qwen2/Qwen3 regex.
    {
        const auto ids = vocab->encode("12");
        const std::vector<int32_t> expected = {49, 50}; // '1','2'
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == "12");
    }

    // Non-Latin script (CJK): no merges are defined for it in this tiny fixture, so it necessarily falls
    // back to raw byte-level tokens -- exactly proving that path works (every UTF-8 byte has some base
    // vocab entry) without needing to hand-trace specific ids. Round-trip is the correctness signal.
    {
        const std::string cjk = "\xE4\xB8\xAD\xE6\x96\x87"; // "中文"
        const auto ids = vocab->encode(cjk);
        LOOM_CHECK(ids.size() == 6); // 2 codepoints * 3 UTF-8 bytes each, one token per raw byte
        LOOM_CHECK(vocab->decode(ids) == cjk);
    }

    // NFC fidelity: a decomposed "e" + combining-acute-accent input must encode/decode as the
    // *precomposed* form (encode() NFC-normalizes before tokenizing) -- proves loom::nfc_normalize is
    // actually wired into BpeVocab::encode, not just unit-tested in isolation (test_unicode.cpp).
    {
        const std::string decomposed = "e\xCC\x81";     // U+0065 U+0301
        const std::string precomposed = "\xC3\xA9";      // U+00E9 "é"
        const auto ids = vocab->encode(decomposed);
        LOOM_CHECK(vocab->decode(ids) == precomposed);
        LOOM_CHECK(loom::nfc_normalize(decomposed) == precomposed);
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
