// Milestone-2 vision encoder end-to-end correctness test: loads the toy vision encoder GGUF generated by
// tools/fixture_gen/make_toy_vision_gguf.py, runs a single non-autoregressive forward pass through
// GraphBuilder directly (no Generator/KvCache -- encoders process the whole fixed-length input in one
// shot), and compares the output hidden states against reference_forward_vision.py's independent numpy
// computation of the identical weights/topology/image.

#include "test_util.h"

#include "loom/loom.h"

#include <ggml-cpu.h>

#include <algorithm>
#include <cmath>
#include <fstream>

namespace {

std::vector<float> read_f32_binary(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    f.seekg(0, std::ios::end);
    const std::streamsize bytes = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<float> data(static_cast<size_t>(bytes) / sizeof(float));
    f.read(reinterpret_cast<char*>(data.data()), bytes);
    return data;
}

} // namespace

int main() {
    ggml_backend_ptr backend(ggml_backend_cpu_init());
    LOOM_CHECK(backend != nullptr);

    const std::string gguf_path = std::string(LOOM_TEST_FIXTURE_DIR) + "/toy_vision.gguf";
    const std::string ref_path = std::string(LOOM_TEST_REF_DIR) + "/expected_output.bin";

    auto model = loom::GgufModel::load(gguf_path, backend.get());
    loom::GraphTopology topo = loom::GraphTopology::parse(model->topology_json());

    constexpr uint32_t kNTokens = 4; // patches: (8/4) x (8/4)
    constexpr uint32_t kNEmbd = 8;

    // No KvCache: this topology's ATTENTION nodes all set "kv_cache": false.
    loom::GraphBuilder builder(topo, *model, backend.get(), /*kv_cache=*/nullptr);
    const loom::GraphBuilder::BuildResult& result = builder.build({{"n_tokens", kNTokens}, {"n_past", /*n_past=*/0}});

    // The image itself is baked into the GGUF as a weight ("image.data"); the only runtime input this
    // topology declares is the (all-zero, fully-unmasked) attention mask.
    ggml_tensor* mask = result.input_tensors.at("kq_mask");
    const std::vector<float> zero_mask(kNTokens * kNTokens, 0.0f);
    ggml_backend_tensor_set(mask, zero_mask.data(), 0, zero_mask.size() * sizeof(float));

    ggml_backend_graph_compute(backend.get(), result.graph);

    LOOM_CHECK(result.output->ne[0] == kNEmbd);
    LOOM_CHECK(result.output->ne[1] == kNTokens);

    std::vector<float> actual(kNEmbd * kNTokens);
    ggml_backend_tensor_get(result.output, actual.data(), 0, actual.size() * sizeof(float));

    const std::vector<float> expected = read_f32_binary(ref_path);
    LOOM_CHECK(expected.size() == actual.size());

    float max_abs_diff = 0.0f;
    for (size_t i = 0; i < expected.size() && i < actual.size(); ++i) {
        max_abs_diff = std::max(max_abs_diff, std::fabs(expected[i] - actual[i]));
    }
    LOOM_CHECK(max_abs_diff <= 1e-3f);
    if (max_abs_diff > 1e-3f) {
        std::fprintf(stderr, "max abs diff = %f\n", static_cast<double>(max_abs_diff));
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
