// Milestone-3 VAE decoder end-to-end correctness test: loads the toy VAE decoder GGUF generated by
// tools/fixture_gen/make_toy_vae_gguf.py, runs a single one-shot forward pass through GraphBuilder
// directly (no control flow needed -- a VAE decoder is a plain DAG, matching BACKLOG.md), and compares
// the output against reference_forward_vae.py's independent numpy computation of the identical
// weights/latent.

#include "test_util.h"

#include "loom/loom.h"

#include <ggml-cpu.h>

#include <algorithm>
#include <cmath>
#include <fstream>

namespace {

std::vector<float> read_f32_binary(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    f.seekg(0, std::ios::end);
    const std::streamsize bytes = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<float> data(static_cast<size_t>(bytes) / sizeof(float));
    f.read(reinterpret_cast<char*>(data.data()), bytes);
    return data;
}

} // namespace

int main() {
    ggml_backend_ptr backend(ggml_backend_cpu_init());
    LOOM_CHECK(backend != nullptr);

    const std::string gguf_path = std::string(LOOM_TEST_FIXTURE_DIR) + "/toy_vae.gguf";
    const std::string ref_path = std::string(LOOM_TEST_REF_DIR) + "/expected_output.bin";

    auto model = loom::GgufModel::load(gguf_path, backend.get());
    loom::GraphTopology topo = loom::GraphTopology::parse(model->topology_json());

    constexpr uint32_t kNEmbd = 8;
    constexpr uint32_t kTOut = 10; // (4-1)*2 + 4

    // No declared inputs at all: weights and the fixed latent are all resolved from the Symbol Table.
    loom::GraphBuilder builder(topo, *model, backend.get(), /*kv_cache=*/nullptr);
    loom::GraphBuilder::BuildResult result = builder.build({{"n_tokens", /*n_tokens=*/1}, {"n_past", /*n_past=*/0}});

    ggml_backend_graph_compute(backend.get(), result.graph);

    LOOM_CHECK(result.output->ne[0] == kTOut);
    LOOM_CHECK(result.output->ne[1] == kNEmbd);

    std::vector<float> actual(kNEmbd * kTOut);
    ggml_backend_tensor_get(result.output, actual.data(), 0, actual.size() * sizeof(float));

    const std::vector<float> expected = read_f32_binary(ref_path);
    LOOM_CHECK(expected.size() == actual.size());

    float max_abs_diff = 0.0f;
    for (size_t i = 0; i < expected.size() && i < actual.size(); ++i) {
        max_abs_diff = std::max(max_abs_diff, std::fabs(expected[i] - actual[i]));
    }
    LOOM_CHECK(max_abs_diff <= 1e-3f);
    if (max_abs_diff > 1e-3f) {
        std::fprintf(stderr, "max abs diff = %f\n", static_cast<double>(max_abs_diff));
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
