// Loads the attention-free toy model generated by tests/fixtures/make_builder_test_gguf.py and checks
// that GraphBuilder::build() produces correctly-shaped graphs across several (n_tokens, n_past)
// combinations, correctly expands the repeat_for block, and surfaces the right error types for a bad
// topology.

#include "test_util.h"

#include "loom/loom.h"

#include <ggml-cpu.h>

namespace {

constexpr int kNVocab = 6;
constexpr int kNEmbd = 4;

void test_shapes_across_calls(loom::GgufModel& model, ggml_backend_t backend) {
    loom::GraphTopology topo = loom::GraphTopology::parse(model.topology_json());
    loom::GraphBuilder builder(topo, model, backend);

    for (uint32_t n_tokens : {1u, 3u, 5u}) {
        auto result = builder.build({{"n_tokens", n_tokens}, {"n_past", /*n_past=*/0}});
        LOOM_CHECK(result.graph != nullptr);
        LOOM_CHECK(result.output != nullptr);
        LOOM_CHECK(result.output->ne[0] == kNVocab);
        LOOM_CHECK(result.output->ne[1] == static_cast<int64_t>(n_tokens));

        LOOM_CHECK(result.input_tensors.count("tokens") == 1);
        ggml_tensor* tokens = result.input_tensors.at("tokens");
        LOOM_CHECK(tokens->type == GGML_TYPE_I32);
        LOOM_CHECK(tokens->ne[0] == static_cast<int64_t>(n_tokens));
    }

    // n_past shouldn't affect shapes for this attention-free topology (n_kv isn't referenced by any
    // node), but the build must still succeed -- exercises that n_past/n_kv symbol wiring doesn't break
    // topologies that don't use it.
    auto result = builder.build({{"n_tokens", /*n_tokens=*/1}, {"n_past", /*n_past=*/7}});
    LOOM_CHECK(result.output->ne[1] == 1);
}

void test_unresolved_output_throws(loom::GgufModel& model, ggml_backend_t backend) {
    const char* json = R"JSON({
      "version": 1,
      "inputs": [{"name":"tokens","dtype":"i32","shape":["n_tokens"]}],
      "output": "never_produced",
      "nodes": [
        { "op": "GET_ROWS", "inputs": ["token_embd.weight", "tokens"], "outputs": ["cur"] }
      ]
    })JSON";
    loom::GraphTopology topo = loom::GraphTopology::parse(json);
    loom::GraphBuilder builder(topo, model, backend);
    LOOM_CHECK_THROWS(builder.build({{"n_tokens", 2}, {"n_past", 0}}), loom::SchemaError);
}

void test_unknown_op_throws(loom::GgufModel& model, ggml_backend_t backend) {
    const char* json = R"JSON({
      "version": 1,
      "inputs": [{"name":"tokens","dtype":"i32","shape":["n_tokens"]}],
      "output": "cur",
      "nodes": [
        { "op": "NOT_A_REAL_OP", "inputs": ["tokens"], "outputs": ["cur"] }
      ]
    })JSON";
    loom::GraphTopology topo = loom::GraphTopology::parse(json);
    loom::GraphBuilder builder(topo, model, backend);
    LOOM_CHECK_THROWS(builder.build({{"n_tokens", 2}, {"n_past", 0}}), loom::UnknownOpError);
}

void test_unresolved_input_throws(loom::GgufModel& model, ggml_backend_t backend) {
    const char* json = R"JSON({
      "version": 1,
      "inputs": [{"name":"tokens","dtype":"i32","shape":["n_tokens"]}],
      "output": "cur",
      "nodes": [
        { "op": "GET_ROWS", "inputs": ["does.not.exist.weight", "tokens"], "outputs": ["cur"] }
      ]
    })JSON";
    loom::GraphTopology topo = loom::GraphTopology::parse(json);
    loom::GraphBuilder builder(topo, model, backend);
    LOOM_CHECK_THROWS(builder.build({{"n_tokens", 2}, {"n_past", 0}}), loom::SchemaError);
}

void test_reserve_does_not_break_subsequent_builds(loom::GgufModel& model, ggml_backend_t backend) {
    loom::GraphTopology topo = loom::GraphTopology::parse(model.topology_json());
    loom::GraphBuilder builder(topo, model, backend);
    builder.reserve(16);
    auto result = builder.build({{"n_tokens", 3}, {"n_past", 0}});
    LOOM_CHECK(result.output->ne[1] == 3);
}

} // namespace

int main() {
    ggml_backend_ptr backend(ggml_backend_cpu_init());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/builder_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());

    test_shapes_across_calls(*model, backend.get());
    test_unresolved_output_throws(*model, backend.get());
    test_unknown_op_throws(*model, backend.get());
    test_unresolved_input_throws(*model, backend.get());
    test_reserve_does_not_break_subsequent_builds(*model, backend.get());

    LOOM_TEST_REPORT_AND_RETURN();
}
