// Milestone-3 ODE-stepper end-to-end correctness test: loads the toy flow-matching vector-field GGUF
// generated by tools/fixture_gen/make_toy_ode_gguf.py, runs OdeStepper::integrate() (per-step rebuild
// forward-Euler loop -- see ode_stepper.h for why), and compares the final integrated latent against
// reference_forward_ode.py's independent numpy computation of the identical weights/loop.

#include "test_util.h"

#include "loom/loom.h"

#include <ggml-cpu.h>

#include <algorithm>
#include <cmath>
#include <fstream>

namespace {

std::vector<float> read_f32_binary(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    f.seekg(0, std::ios::end);
    const std::streamsize bytes = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<float> data(static_cast<size_t>(bytes) / sizeof(float));
    f.read(reinterpret_cast<char*>(data.data()), bytes);
    return data;
}

std::vector<float> read_weight_as_f32(loom::GgufModel& model, const std::string& name) {
    ggml_tensor* t = model.weight(name);
    std::vector<float> data(static_cast<size_t>(ggml_nelements(t)));
    ggml_backend_tensor_get(t, data.data(), 0, data.size() * sizeof(float));
    return data;
}

} // namespace

int main() {
    ggml_backend_ptr backend(ggml_backend_cpu_init());
    LOOM_CHECK(backend != nullptr);

    const std::string gguf_path = std::string(LOOM_TEST_FIXTURE_DIR) + "/toy_ode.gguf";
    const std::string ref_path = std::string(LOOM_TEST_REF_DIR) + "/expected_final_latent.bin";

    auto model = loom::GgufModel::load(gguf_path, backend.get());
    loom::GraphTopology topo = loom::GraphTopology::parse(model->topology_json());

    // Baked into the GGUF (see make_toy_ode_gguf.py) so the C++ side and reference_forward_ode.py are
    // guaranteed to start from byte-identical initial state without a second data-transfer mechanism.
    const std::vector<float> initial_latent = read_weight_as_f32(*model, "initial_latent.data");
    const std::vector<float> conditioning = read_weight_as_f32(*model, "conditioning.data");
    LOOM_CHECK(initial_latent.size() == 64); // n_tokens=8 * n_embd=8
    LOOM_CHECK(conditioning.size() == 8);

    loom::OdeStepper stepper(*model, topo, backend.get());

    loom::OdeStepConfig cfg;
    cfg.n_steps = 8;
    cfg.t_start = 0.0f;
    cfg.t_end = 1.0f;

    int step_count = 0;
    cfg.on_step = [&](float /*t*/, const std::vector<float>& velocity) {
        ++step_count;
        LOOM_CHECK(velocity.size() == initial_latent.size());
    };

    std::vector<float> final_latent = stepper.integrate(initial_latent, conditioning, cfg);
    LOOM_CHECK(step_count == static_cast<int>(cfg.n_steps));
    LOOM_CHECK(final_latent.size() == initial_latent.size());

    const std::vector<float> expected = read_f32_binary(ref_path);
    LOOM_CHECK(expected.size() == final_latent.size());

    float max_abs_diff = 0.0f;
    for (size_t i = 0; i < expected.size() && i < final_latent.size(); ++i) {
        max_abs_diff = std::max(max_abs_diff, std::fabs(expected[i] - final_latent[i]));
    }
    LOOM_CHECK(max_abs_diff <= 1e-3f);
    if (max_abs_diff > 1e-3f) {
        std::fprintf(stderr, "max abs diff = %f\n", static_cast<double>(max_abs_diff));
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
