// Integration smoke test for Phase 3: loads the tiny single-layer attention fixture generated by
// tests/fixtures/make_attention_test_gguf.py and runs Generator::generate() end-to-end, exercising
// GraphBuilder + the ATTENTION primitive + KvCache + the autoregressive while-loop together. Checks
// shapes/ranges and determinism -- numeric correctness against a numpy reference is Phase 4's job (a
// larger, purpose-built fixture), this just confirms the KV-cache write-before-read ordering and the
// generation loop don't silently produce garbage or crash.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

namespace {
constexpr int32_t kNVocab = 8;
}

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/attention_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    loom::GraphTopology topo = loom::GraphTopology::parse(model->topology_json());

    loom::GenerationConfig cfg;
    cfg.max_new_tokens = 5;
    cfg.n_ctx_max = 16;

    loom::Generator gen(*model, topo, cfg, backend.get());

    const std::vector<int32_t> prompt = {1, 2, 3};
    std::vector<int32_t> out1 = gen.generate(prompt);
    LOOM_CHECK(out1.size() == cfg.max_new_tokens);

    bool in_range = true;
    for (int32_t tok : out1) {
        if (tok < 0 || tok >= kNVocab) in_range = false;
    }
    LOOM_CHECK(in_range);

    // Generator resets its KV cache/position state at the start of generate(), so repeating the same
    // prompt through the same (stateless, greedy) instance must reproduce the same output exactly.
    std::vector<int32_t> out2 = gen.generate(prompt);
    LOOM_CHECK(out1 == out2);

    // A single-token prompt should also work (exercises the n_tokens=1 prefill edge case).
    std::vector<int32_t> out3 = gen.generate({0});
    LOOM_CHECK(out3.size() == cfg.max_new_tokens);

    LOOM_TEST_REPORT_AND_RETURN();
}
