// GQA (grouped-query attention) + QK-norm regression test: loads the gqa_test.gguf fixture generated by
// tools/fixture_gen/make_gqa_test_gguf.py (4 query heads sharing 2 KV heads, 2:1 grouping, plus a
// per-head RMSNorm on q/k before RoPE -- unlike the toy LLM fixture, which has neither), runs it through
// Generator::generate(), and compares every generated step's logits against
// tools/fixture_gen/reference_forward_gqa.py's independent numpy computation. Written BEFORE converting
// the real Qwen3-0.6B-Base checkpoint (16 query / 8 KV heads, real QK-norm weights) so both mechanisms
// are proven correct in isolation first, per BACKLOG.md's "verify before trusting an existing mechanism
// in a new configuration" discipline -- same role test_graph_reuse_safety.cpp played for the ggml
// graph-reuse finding.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"
#include <nlohmann/json.hpp>

#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>

namespace {

std::string read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

std::vector<float> read_f32_binary(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    f.seekg(0, std::ios::end);
    const std::streamsize bytes = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<float> data(static_cast<size_t>(bytes) / sizeof(float));
    f.read(reinterpret_cast<char*>(data.data()), bytes);
    return data;
}

} // namespace

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    const std::string gguf_path = std::string(LOOM_TEST_FIXTURE_DIR) + "/gqa_test.gguf";
    const std::string ref_dir = LOOM_TEST_REF_DIR;

    auto model = loom::GgufModel::load(gguf_path, backend.get());
    LOOM_CHECK(model->hparam_u32("n_head") == 4);
    LOOM_CHECK(model->hparam_u32("n_head_kv") == 2); // the whole point of this fixture

    loom::GraphTopology topo = loom::GraphTopology::parse(model->topology_json());

    const std::vector<int32_t> prompt = {1, 2, 3};
    constexpr uint32_t kNNew = 4;

    std::vector<std::vector<float>> actual_logits;
    loom::GenerationConfig cfg;
    cfg.max_new_tokens = kNNew;
    cfg.n_ctx_max = 32;
    cfg.on_token = [&](const std::vector<float>& row) { actual_logits.push_back(row); };

    loom::Generator gen(*model, topo, cfg, backend.get());
    std::vector<int32_t> tokens = gen.generate(prompt);

    LOOM_CHECK(tokens.size() == kNNew);
    LOOM_CHECK(actual_logits.size() == kNNew);

    nlohmann::json expected_tokens_json = nlohmann::json::parse(read_file(ref_dir + "/expected_generated_tokens.json"));
    const std::vector<int32_t> expected_tokens = expected_tokens_json.get<std::vector<int32_t>>();
    LOOM_CHECK(tokens == expected_tokens);

    for (uint32_t step = 0; step < kNNew; ++step) {
        const std::vector<float> expected = read_f32_binary(ref_dir + "/expected_logits_step" + std::to_string(step) + ".bin");
        LOOM_CHECK(expected.size() == actual_logits[step].size());

        bool close = true;
        float max_abs_diff = 0.0f;
        for (size_t i = 0; i < expected.size() && i < actual_logits[step].size(); ++i) {
            const float diff = std::fabs(expected[i] - actual_logits[step][i]);
            max_abs_diff = std::max(max_abs_diff, diff);
            if (diff > 1e-3f) close = false;
        }
        LOOM_CHECK(close);
        if (!close) {
            std::fprintf(stderr, "step %u: max abs logit diff = %f\n", step, static_cast<double>(max_abs_diff));
        }
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
