// Tests loom::CosyVoice3Vocab (src/core/cosyvoice3_vocab.cpp) against the synthetic fixture generated by
// tests/fixtures/make_cosyvoice3_vocab_gguf.py.
//
// **The measured claim is that `encode` IS the reference's text path** -- `text_normalize(split=True)`
// as the release runs it without ttsfrd/wetext, then the tokenizer per piece, each piece opened by
// `<|endoftext|>` -- and that comparison lives where the reference can run: against the real Qwen2
// tokenizer, 9000/9000 texts over nine input classes (prose with numbers, long English, Chinese, long
// Chinese, mixed, markup, tags, exotic digits and spaces, punctuation soup), two seeds, with the
// reference's crashes compared as refusals. Three sabotaged references (numbers not spelled, a budget
// one token wider, `replace_blank` skipped) each go red. What belongs here is each rule, one case
// apiece, on a table whose id count is a byte count and whose budgets are 12/6/4.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

#include <string>
#include <vector>

using Ids = std::vector<int32_t>;
using Strings = std::vector<std::string>;

namespace {

constexpr int32_t kHeader = 256, kEndOfPrompt = 257, kBreath = 258, kXy = 259, kNbsp = 260, kNbsp2 = 261;

// No merges reach these texts, so a text's ids are its UTF-8 bytes.
Ids bytes(const std::string& text) {
    Ids ids;
    for (unsigned char c : text) ids.push_back(c);
    return ids;
}

Ids chunked(const Strings& pieces) {
    Ids ids;
    for (const std::string& piece : pieces) {
        ids.push_back(kHeader);
        const Ids b = bytes(piece);
        ids.insert(ids.end(), b.begin(), b.end());
    }
    return ids;
}

bool throws_on(const loom::CosyVoice3Vocab& vocab, const std::string& text) {
    try {
        vocab.encode(text);
    } catch (const loom::Error&) {
        return true;
    }
    return false;
}

} // namespace

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);
    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/cosyvoice3_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    auto vocab = loom::CosyVoice3Vocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 262);
    LOOM_CHECK(vocab->chunk_header() == kHeader);

    // --- inflect's number_to_words, on digit runs ---
    auto words = [&](const std::string& run) { return vocab->spell_out_number(run); };
    LOOM_CHECK(words("0") == "zero");
    LOOM_CHECK(words("1") == "one");
    LOOM_CHECK(words("10") == "ten");
    LOOM_CHECK(words("11") == "eleven");
    LOOM_CHECK(words("42") == "forty-two");
    LOOM_CHECK(words("100") == "one hundred");
    LOOM_CHECK(words("101") == "one hundred and one");
    // The "and" before the last word comes from COMMA_WORD, and only when a ", " precedes it.
    LOOM_CHECK(words("1001") == "one thousand and one");
    LOOM_CHECK(words("2026") == "two thousand and twenty-six");
    LOOM_CHECK(words("1998") == "one thousand, nine hundred and ninety-eight");
    LOOM_CHECK(words("1000000") == "one million");
    // Leading ASCII zeros are stripped (`lstrip("0")`) and the rest read as a number.
    LOOM_CHECK(words("0012") == "twelve");
    LOOM_CHECK(words("007") == "seven");
    // Every `isdigit` run is one number, so a decimal point splits it: "three.five", not "three point five".
    LOOM_CHECK(words("3.5") == "three.five");
    // Arabic-Indic digits are `\d`, so inflect reads their values.
    LOOM_CHECK(words("\xd9\xa3\xd9\xa4") == "thirty-four");
    // A superscript is `isdigit` but not `\d`: it joins the run and is then dropped, and a run of
    // nothing but superscripts is "0".
    LOOM_CHECK(words("2\xc2\xb2") == "two");
    LOOM_CHECK(words("m\xc2\xb2") == "mzero");
    LOOM_CHECK(words("a 12 b") == "a twelve b");
    // 37 digits need a twelfth scale word, which inflect does not have (it raises NumOutOfRangeError).
    LOOM_CHECK(throws_on(*vocab, std::string(37, '1')));
    LOOM_CHECK(!throws_on(*vocab, std::string(36, '1')));

    // --- the English path: spell, terminate, split at enders, regroup by token count ---
    LOOM_CHECK((vocab->chunks("hello") == Strings{"hello."}));
    LOOM_CHECK((vocab->chunks("  Hi 12!  ") == Strings{"Hi twelve!"}));
    // 3 + 4 + 4 = 11 tokens fit the budget of 12; the fourth sentence would make 15, and 11 > 6, so the
    // piece closes. The last piece (4 tokens) is not under merge_len (4), so it stands alone...
    LOOM_CHECK((vocab->chunks("Aa. Bb. Cc. Dd.") == Strings{"Aa. Bb. Cc.", " Dd."}));
    LOOM_CHECK((vocab->encode("Aa. Bb. Cc. Dd.") == chunked({"Aa. Bb. Cc.", " Dd."})));
    // ...and a 3-token one is, so it joins the piece before.
    LOOM_CHECK((vocab->chunks("Aa. Bb. Cc. D.") == Strings{"Aa. Bb. Cc. D."}));
    // A closing quote right after an ender stays with its sentence.
    LOOM_CHECK((vocab->chunks("He said \"hi.\" Then") == Strings{"He said \"hi.\"", " Then."}));
    // A closing quote after an ender that ends no sentence pops the reference's empty list.
    LOOM_CHECK(throws_on(*vocab, ".\"abc"));
    // Pieces of nothing but punctuation are dropped; a text of nothing else has nothing to say.
    LOOM_CHECK(vocab->chunks("...").empty());
    LOOM_CHECK(throws_on(*vocab, "..."));
    LOOM_CHECK(throws_on(*vocab, ""));
    LOOM_CHECK(throws_on(*vocab, " \n\t"));
    // Added tokens survive the path and are matched whole.
    LOOM_CHECK((vocab->encode("[breath] hi") == Ids{kHeader, kBreath, ' ', 'h', 'i', '.'}));

    // --- the Chinese path: no spelling, blanks dropped, the replacement table, character budgets ---
    // "你好 世界 A B，": a space survives only between two ASCII non-spaces, and a trailing comma
    // becomes the full stop.
    LOOM_CHECK((vocab->chunks("\xe4\xbd\xa0\xe5\xa5\xbd \xe4\xb8\x96\xe7\x95\x8c A B\xef\xbc\x8c") ==
                Strings{"\xe4\xbd\xa0\xe5\xa5\xbd\xe4\xb8\x96\xe7\x95\x8c" "A B\xe3\x80\x82"}));
    // "面积3²（大约） - 很大.": replace_blank runs FIRST, so " - " has already lost its spaces and the
    // " - " -> "，" rule never sees it; "²" -> "平方", brackets removed, "." -> "。". Digits are kept.
    LOOM_CHECK((vocab->chunks("\xe9\x9d\xa2\xe7\xa7\xaf" "3\xc2\xb2\xef\xbc\x88\xe5\xa4\xa7\xe7\xba\xa6\xef\xbc\x89"
                              " - \xe5\xbe\x88\xe5\xa4\xa7.") ==
                Strings{"\xe9\x9d\xa2\xe7\xa7\xaf" "3\xe5\xb9\xb3\xe6\x96\xb9\xe5\xa4\xa7\xe7\xba\xa6-"
                        "\xe5\xbe\x88\xe5\xa4\xa7\xe3\x80\x82"}));
    // Six 3-character sentences, counted in CHARACTERS: 12 fit, the fifth would make 15, and the last
    // two (6) are not under merge_len. Five would leave one (3) that joins the piece before.
    const std::string s = "\xe4\xb8\x80\xe4\xba\x8c\xe3\x80\x82";  // "一二。"
    LOOM_CHECK((vocab->chunks(s + s + s + s + s + s) == Strings{s + s + s + s, s + s}));
    LOOM_CHECK((vocab->chunks(s + s + s + s + s) == Strings{s + s + s + s + s}));

    // --- markup skips the front end, whole and unstripped ---
    LOOM_CHECK((vocab->chunks(" <|endofprompt|> 12 ") == Strings{" <|endofprompt|> 12 "}));
    LOOM_CHECK((vocab->encode("<|endofprompt|>1") == Ids{kHeader, kEndOfPrompt, '1'}));
    // Only one of the two halves is not markup.
    LOOM_CHECK((vocab->chunks("a <| 1") == Strings{"a <| one."}));
    // A marked-up text that spells the chunk header itself is refused: the driver would split on it.
    LOOM_CHECK(throws_on(*vocab, "<|endoftext|>hi"));

    // --- the BPE underneath, and decode ---
    LOOM_CHECK((vocab->encode("xy") == Ids{kHeader, kXy, '.'}));
    // `\s` is Unicode's White_Space, as in `tokenizers`: two NBSPs before a letter are `\s+(?!\S)` (one)
    // then a letter run with the other as its prefix -- never one `[^\s\p{L}\p{N}]` run, which the pair's
    // merge would turn into kNbsp2. With an ASCII-only `\s` they were, and 2 of 900 exotic texts differed.
    LOOM_CHECK((vocab->encode("<|x|>a\xc2\xa0\xc2\xa0" "b") ==
                Ids{kHeader, '<', '|', 'x', '|', '>', 'a', kNbsp, kNbsp, 'b'}));
    LOOM_CHECK(vocab->decode(vocab->encode("Aa. Bb. Cc. Dd.")) == "Aa. Bb. Cc. Dd.");

    // A file of another family is declined, not misread.
    auto other = loom::GgufModel::load(std::string(LOOM_TEST_FIXTURE_DIR) + "/ctc_vocab_test.gguf", backend.get());
    LOOM_CHECK(loom::CosyVoice3Vocab::load(*other) == nullptr);

    LOOM_TEST_REPORT_AND_RETURN();
}
