// Smoke test for GgufModel: loads the ad hoc minimal fixture generated by
// tests/fixtures/make_minimal_gguf.py and exercises every accessor.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

#include <string>
#include <vector>

namespace {
// Kept in sync with tests/fixtures/make_minimal_gguf.py.
const std::string kExpectedTopologyJson = R"({"version": 1, "nodes": []})";
const std::string kExpectedOtherTopologyJson = R"({"version": 1, "nodes": [], "note": "other"})";
} // namespace

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/minimal.gguf";

    auto model = loom::GgufModel::load(path, backend.get());
    LOOM_CHECK(model != nullptr);

    // -- weights --
    LOOM_CHECK(model->has_weight("test.weight"));
    LOOM_CHECK(!model->has_weight("does.not.exist"));

    ggml_tensor* w = model->weight("test.weight");
    LOOM_CHECK(w != nullptr);
    LOOM_CHECK(w->ne[0] == 4);
    LOOM_CHECK(w->ne[1] == 3);

    std::vector<float> data(12);
    ggml_backend_tensor_get(w, data.data(), 0, ggml_nbytes(w));
    bool data_ok = true;
    for (int i = 0; i < 12; ++i) {
        if (data[i] != static_cast<float>(i)) data_ok = false;
    }
    LOOM_CHECK(data_ok);

    LOOM_CHECK_THROWS(model->weight("does.not.exist"), loom::LoadError);

    // -- content-addressed weight aliasing (BACKLOG.md P0.2) -- "test.weight_alias" has no tensor_info
    //    of its own in the fixture, only a "loom.tensor_alias.*" KV pair pointing at "test.weight"; it
    //    must resolve to the EXACT SAME ggml_tensor* (not merely equal data), proving the alias is
    //    wired into `symbols_` rather than materializing a second copy. --
    LOOM_CHECK(model->has_weight("test.weight_alias"));
    LOOM_CHECK(model->weight("test.weight_alias") == w);

    // -- hparams --
    LOOM_CHECK(model->architecture() == "minimal_test");
    LOOM_CHECK(model->hparam_u32("n_layer") == 2);
    LOOM_CHECK_NEAR(model->hparam_f32("scale"), 0.5, 1e-6);
    LOOM_CHECK_THROWS(model->hparam_u32("does_not_exist"), loom::LoadError);
    LOOM_CHECK_THROWS(model->hparam_f32("architecture"), loom::LoadError); // wrong type (string, not f32)

    // -- topology --
    LOOM_CHECK(model->topology_json() == kExpectedTopologyJson);

    // -- named (multi-topology) support, added for Whisper's own single-GGUF-file convention (see
    //    LOOM_PROCEDURAL_GENERALIZATION.md) -- the bare topology_json() above is unaffected by a named
    //    topology also being present in the same file. --
    LOOM_CHECK(model->has_topology("other"));
    LOOM_CHECK(!model->has_topology("does_not_exist"));
    LOOM_CHECK(model->topology_json("other") == kExpectedOtherTopologyJson);
    LOOM_CHECK_THROWS(model->topology_json("does_not_exist"), loom::LoadError);

    // -- hparam_env() --
    loom::SymbolEnv env = model->hparam_env();
    LOOM_CHECK(env.has("n_layer"));
    LOOM_CHECK_NEAR(env.get("n_layer"), 2.0, 1e-9);
    LOOM_CHECK(env.has("scale"));
    LOOM_CHECK_NEAR(env.get("scale"), 0.5, 1e-9);
    LOOM_CHECK(!env.has("architecture")); // string KV, not symbol-evaluable, must be skipped

    // -- SymbolEnv expression evaluation (independent of GgufModel, exercised here for convenience) --
    env.set("n_embd_head_k", 16.0);
    LOOM_CHECK_NEAR(env.eval("$n_layer"), 2.0, 1e-9);
    LOOM_CHECK_NEAR(env.eval("1/sqrt($n_embd_head_k)"), 0.25, 1e-9);
    LOOM_CHECK_NEAR(env.eval("(1 + 3) * 2"), 8.0, 1e-9);

    // -- floor(), added for deriving conv-stride output lengths (e.g. Conformer-CTC's dynamic
    //    n_subsampled/n_pos) from a runtime symbol -- must truncate, not round-to-nearest. --
    LOOM_CHECK_NEAR(env.eval("floor(7.9)"), 7.0, 1e-9);
    LOOM_CHECK_NEAR(env.eval("floor(-1.5)"), -2.0, 1e-9);
    env.set("n_tokens", 65.0);
    // Conv-stride output-length formula (pad=1, kernel=3, stride=2): floor((65+2-3)/2)+1 = floor(32)+1 = 33.
    LOOM_CHECK_NEAR(env.eval("floor(($n_tokens + 2 - 3)/2) + 1"), 33.0, 1e-9);
    // A halfway case where floor and round-to-nearest-away-from-zero would disagree: (64-1)/2 = 31.5.
    env.set("n_even", 64.0);
    LOOM_CHECK_NEAR(env.eval("floor(($n_even - 1)/2) + 1"), 32.0, 1e-9); // floor(31.5)+1 = 32, NOT llround's 33

    // -- generic KV accessors (added for the tokenizer.ggml.* vocab schema) --
    LOOM_CHECK(model->has_kv("test.flag_true"));
    LOOM_CHECK(!model->has_kv("test.does_not_exist"));
    LOOM_CHECK(model->kv_bool("test.flag_true", false) == true);
    LOOM_CHECK(model->kv_bool("test.does_not_exist", true) == true); // missing -> default
    LOOM_CHECK(model->kv_i32("test.does_not_exist", -7) == -7);      // missing -> default
    LOOM_CHECK_THROWS(model->kv_bool("loom.n_layer", false), loom::LoadError); // wrong type (u32, not bool)

    const std::vector<std::string> arr_str = model->kv_arr_str("test.arr_str");
    LOOM_CHECK((arr_str == std::vector<std::string>{"alpha", "beta", "gamma"}));

    const std::vector<float> arr_f32 = model->kv_arr_f32("test.arr_f32");
    LOOM_CHECK((arr_f32 == std::vector<float>{1.5f, 2.5f, 3.5f}));

    const std::vector<int32_t> arr_i32 = model->kv_arr_i32("test.arr_i32");
    LOOM_CHECK((arr_i32 == std::vector<int32_t>{10, -20, 30}));

    LOOM_CHECK_THROWS(model->kv_arr_str("test.does_not_exist"), loom::LoadError);
    LOOM_CHECK_THROWS(model->kv_arr_f32("test.arr_str"), loom::LoadError); // wrong element type

    // -- error paths --
    LOOM_CHECK_THROWS(loom::GgufModel::load("/nonexistent/path/to/model.gguf", backend.get()), loom::LoadError);

    LOOM_TEST_REPORT_AND_RETURN();
}
