// Tests loom::CtcVocab (src/core/ctc_vocab.cpp) against the small synthetic CTC-character fixture
// generated by tests/fixtures/make_ctc_vocab_gguf.py, whose table is a real `Wav2Vec2CTCTokenizer`
// one truncated to the letters spelled below.
//
// The ids here are what a CTC head's argmax produces AFTER the driver's own collapse -- consecutive
// duplicates dropped, blank dropped (driver_components.CtcGreedyEpilogue) -- which is why no test below
// feeds a repeat or a blank: by the time a vocabulary sees them they are gone, and asserting on them
// here would be asserting on the epilogue in the wrong file.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/ctc_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    LOOM_CHECK(model != nullptr);

    auto vocab = loom::CtcVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 13);
    LOOM_CHECK(vocab->blank_id() == 0);
    LOOM_CHECK(vocab->unk_id() == 3);
    LOOM_CHECK(vocab->word_delimiter_id() == 4);

    // The delimiter becomes a space and every other piece is concatenated: "NOT|A|HOLE" -> "NOT A HOLE".
    // This is `Wav2Vec2CTCTokenizer.convert_tokens_to_string` minus the collapse the driver already did.
    LOOM_CHECK(vocab->decode({9, 8, 6, 4, 7, 4, 10, 8, 11, 5}) == "NOT A HOLE");

    // A delimiter at either end is a real space, not trimmed. HF does not trim it either, and the CTC
    // head genuinely emits one where the utterance starts on a word boundary -- so trimming here would
    // be this file editing a transcript.
    LOOM_CHECK(vocab->decode({4, 9, 8, 4}) == " NO ");

    // The pieces are the CHECKPOINT'S, which is the whole argument for a tag of its own rather than a
    // "t5" file with the delimiter rewritten to U+2581 (see include/loom/core/ctc_vocab.h).
    LOOM_CHECK(vocab->id_to_piece(4) == "|");
    LOOM_CHECK(vocab->id_to_piece(0) == "<pad>");

    // An empty decode is the empty string -- an utterance the head called blank at every frame, which
    // is what silence produces and is not an error.
    LOOM_CHECK(vocab->decode({}).empty());

    // An id past the end of the table cannot have come from this head, so it raises rather than
    // rendering as nothing.
    {
        bool threw = false;
        try {
            vocab->decode({13});
        } catch (const loom::LoadError&) {
            threw = true;
        }
        LOOM_CHECK(threw);
    }

    // A file of another schema is declined, not claimed -- the contract every vocab loader but
    // `Vocab::load` follows, and what lets `transcribe` try three of them in order.
    {
        const std::string byte_path = std::string(LOOM_TEST_FIXTURE_DIR) + "/byte_vocab_test.gguf";
        auto other = loom::GgufModel::load(byte_path, backend.get());
        LOOM_CHECK(loom::CtcVocab::load(*other) == nullptr);
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
