// Tests loom::ChatterboxVocab (src/core/chatterbox_vocab.cpp) against the synthetic fixture generated by
// tests/fixtures/make_chatterbox_vocab_gguf.py.
//
// **The measured claim is that `encode` IS `EnTokenizer.text_to_tokens(punc_norm(text))`**, and that
// comparison lives where the reference can run: against the real `tokenizer.json`, 3000/3000 texts
// across six input classes (prose, lower-case starts, event tags, random table characters,
// out-of-vocabulary mixes, whitespace edges). What belongs here is each step of the path, one case
// apiece, on a table small enough that every expected id is derivable by hand.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

#include <string>
#include <vector>

using Ids = std::vector<int32_t>;

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);
    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/chatterbox_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    LOOM_CHECK(model != nullptr);
    auto vocab = loom::ChatterboxVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 21);
    LOOM_CHECK(vocab->unk_id() == 1);

    // BPE by merge RANK: "the" merges `t h` (rank 0) then `th e` (rank 1); "then" stops at "the"+"n"
    // because there is no `the n`; "ant" takes `a n` and leaves the `t`. Spaces are `[SPACE]`, and the
    // terminal full stop is added because the text does not end in an ender.
    LOOM_CHECK((vocab->encode("Hi the ant") == Ids{7, 8, 2, 15, 2, 16, 9, 4}));
    LOOM_CHECK((vocab->encode("Hi then") == Ids{7, 8, 2, 15, 13, 4}));

    // A lower-case first character is upper-cased -- and by the FILE's table, which is Python's full
    // mapping: `ß` becomes two codepoints, `SS`.
    LOOM_CHECK((vocab->encode("i hit") == Ids{18, 2, 10, 8, 9, 4}));
    LOOM_CHECK(vocab->normalize("ßa") == "SSa.");
    LOOM_CHECK((vocab->encode("ßa") == Ids{19, 19, 12, 4}));

    // An added token is matched by its literal spelling before pre-tokenization.
    LOOM_CHECK((vocab->encode("Hi [laughter] ha") == Ids{7, 8, 2, 3, 2, 10, 12, 4}));

    // Word and punctuation characters are separate pre-tokens, so no merge crosses a full stop.
    LOOM_CHECK((vocab->encode("Hi.the") == Ids{7, 8, 4, 15, 4}));

    // Characters with no row are one `[UNK]` each, and counted.
    size_t unknown = 0;
    LOOM_CHECK((vocab->encode("Hi xz", &unknown) == Ids{7, 8, 2, 1, 1, 4}));
    LOOM_CHECK(unknown == 2);

    // `punc_norm`: replacements in order, then strip, then an ender check. `;` becomes `, ` AFTER the
    // whitespace collapse, so two spaces survive -- the reference's own quirk, reproduced.
    LOOM_CHECK(vocab->normalize("Hi; the") == "Hi,  the.");
    LOOM_CHECK((vocab->encode("Hi; the") == Ids{7, 8, 5, 2, 2, 15, 4}));
    LOOM_CHECK((vocab->encode("Hi,") == Ids{7, 8, 5}));
    LOOM_CHECK((vocab->encode("Hi -") == Ids{7, 8, 2, 17}));
    LOOM_CHECK((vocab->encode("Hi...") == Ids{7, 8, 5}));
    LOOM_CHECK(vocab->normalize("  Hi \t the  ") == "Hi the.");
    // An empty text is the file's stand-in sentence, not an empty id list.
    LOOM_CHECK((vocab->encode("") == Ids{7, 8, 4}));

    // `EnTokenizer.decode`: `[SPACE]` back to a space, the stop token and `[UNK]` dropped.
    LOOM_CHECK(vocab->decode({7, 8, 2, 15, 0, 1}) == "Hi the");

    // Another family's file is declined rather than misread: a null, not a throw, so a host can try
    // each family in turn.
    {
        auto other = loom::GgufModel::load(std::string(LOOM_TEST_FIXTURE_DIR) + "/ctc_vocab_test.gguf",
                                           backend.get());
        LOOM_CHECK(loom::ChatterboxVocab::load(*other) == nullptr);
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
