// Tests loom::SupertonicTextVectorizer's TABLE-INDEPENDENT behaviour (src/core/
// supertonic_text_vectorizer.cpp) against the synthetic printable-ASCII fixtures generated by
// tests/fixtures/make_supertonic_vocab_gguf.py -- the inverse map, the derived vocabulary size, and the
// default-language KV.
//
// The preprocessing pipeline's fidelity to the real Python `TextVectorizer` is NOT what this checks: that
// needs the real 65536-entry unicode_indexer.json and real recorded oracle output, and it is exactly what
// gate/test_supertonic_text_vectorizer.cpp already does. This test exists because those two properties
// were previously only reachable with a reference-only checkout present, so a change to the id<->codepoint
// mapping could break every host that decodes and still show a green hermetic suite.
//
// The fixture's table is id == cp - 32 over printable ASCII, so every expected id below is arithmetic
// rather than a recorded constant.

#include "test_util.h"

#include "loom/loom.h"

#include <ggml-cpu.h>

namespace {

constexpr int32_t kFirstCp = 32;

// The fixture's own table, as a function: the id the vectorizer must produce for `c`.
int32_t id_of(char c) { return static_cast<int32_t>(c) - kFirstCp; }

std::vector<int32_t> ids_of(const std::string& s) {
    std::vector<int32_t> ids;
    for (char c : s) ids.push_back(id_of(c));
    return ids;
}

} // namespace

int main() {
    ggml_backend_ptr backend(ggml_backend_cpu_init());
    LOOM_CHECK(backend != nullptr);

    auto load = [&backend](const char* name) {
        auto model = loom::GgufModel::load(std::string(LOOM_TEST_FIXTURE_DIR) + "/" + name, backend.get());
        LOOM_CHECK(model != nullptr);
        return model;
    };

    auto model = load("supertonic_vocab_test.gguf");
    auto vec = loom::SupertonicTextVectorizer::load(*model);
    LOOM_CHECK(vec != nullptr);

    // vocab_size() is the TABLE (one entry per BMP codepoint); n_tokens() is the VOCABULARY, derived from
    // the highest mapped id. The real asset's two numbers are 65536 and 162, and conflating them is the
    // mistake this pair of assertions exists to catch.
    LOOM_CHECK(vec->vocab_size() == 65536);
    LOOM_CHECK(vec->n_tokens() == 126 - 32 + 1);

    // Read from the file, not hardcoded: this fixture declares "es" precisely so that a regression to a
    // baked-in "en" fails here.
    LOOM_CHECK(vec->default_lang() == "es");

    // An omitted lang means default_lang(), which is the whole point of it being declared by the export.
    // "hi" gains a trailing "." (no terminal punctuation) and the <es>...</es> wrap.
    {
        const auto implicit = vec->tokenize("hi");
        LOOM_CHECK(implicit == ids_of("<es>hi.</es>"));
        LOOM_CHECK(implicit == vec->tokenize("hi", "es"));  // explicit and implicit agree
        LOOM_CHECK(vec->tokenize("hi", "ko") == ids_of("<ko>hi.</ko>"));  // an explicit lang still wins
    }

    // Round-trip: detokenize is the exact inverse of the codepoint lookup, wrap and inserted period
    // included -- it undoes the TABLE, not the preprocessing, and saying so is the point of asserting the
    // full wrapped string rather than "hi".
    {
        const auto ids = vec->tokenize("hi");
        LOOM_CHECK(vec->detokenize(ids) == "<es>hi.</es>");
    }

    // An id no codepoint reaches is dropped, same silent filter tokenize() applies to an unsupported
    // codepoint. The fixture's highest id is 94, so 95 is unreachable by construction.
    LOOM_CHECK(vec->detokenize({id_of('h'), 95, id_of('i')}) == "hi");
    LOOM_CHECK(vec->detokenize({-1, id_of('h')}) == "h");
    LOOM_CHECK(vec->detokenize({}).empty());

    // The second fixture: no default_lang KV at all, and a table that sends 'A' and 'B' to one id.
    {
        auto ni_model = load("supertonic_vocab_noninjective.gguf");
        auto ni = loom::SupertonicTextVectorizer::load(*ni_model);
        LOOM_CHECK(ni != nullptr);

        // Absent KV falls back to "en" -- the real tokenize_str's own default.
        LOOM_CHECK(ni->default_lang() == "en");
        LOOM_CHECK(ni->tokenize("hi") == ids_of("<en>hi.</en>"));

        // Encoding still works (the collision only makes the direction that needs the inverse ambiguous),
        // and decoding refuses rather than guessing which of the two collided characters was meant.
        LOOM_CHECK(ni->tokenize("AB") == std::vector<int32_t>({id_of('<'), id_of('e'), id_of('n'),
                                                                id_of('>'), id_of('A'), id_of('A'),
                                                                id_of('.'), id_of('<'), id_of('/'),
                                                                id_of('e'), id_of('n'), id_of('>')}));
        bool threw = false;
        try {
            ni->detokenize({id_of('A')});
        } catch (const loom::SchemaError&) {
            threw = true;
        }
        LOOM_CHECK(threw);
    }

    // A GGUF with some OTHER tokenizer family must not be claimed by this class -- the dispatch every
    // host does is by tag, and load() returning non-null for a "byt5" file would silently win it.
    {
        auto other = load("byte_vocab_test.gguf");
        LOOM_CHECK(loom::SupertonicTextVectorizer::load(*other) == nullptr);
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
