// Tests loom::BpeVocab (src/core/bpe_vocab.cpp) against the small synthetic fixture generated by
// tests/fixtures/make_bpe_vocab_gguf.py -- exact hand-traced token ids for plain-ASCII cases (word fully
// reduced by merges, space-prefixed word with no merges, a contraction split, digit-by-digit number
// splitting), plus round-trip checks (decode(encode(x)) == nfc_normalize(x)) for the full-Unicode-fidelity
// cases (CJK, NFC recomposition) that don't have hand-traceable ids against this tiny fixture vocab.

#include "test_util.h"

#include "loom/loom.h"
#include "loom/core/bpe_vocab.h"
#include "loom/core/unicode.h"

#include "cpu_backend.h"

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/bpe_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    LOOM_CHECK(model != nullptr);

    auto vocab = loom::BpeVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 261); // 256 base byte tokens + "ll","he","hell","hello","12"
    LOOM_CHECK(vocab->bos_id() == 0);
    LOOM_CHECK(vocab->eos_id() == 1);

    // "hello" fully reduces via the fixture's 4 merges to a single token, id 259 (256 base + 4th extra).
    {
        const auto ids = vocab->encode("hello");
        const std::vector<int32_t> expected = {259};
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == "hello");
    }

    // " world": leading space attaches to the following letter run (regex alternative 2's optional
    // prefix), but no merge rule matches any adjacent pair here -- 6 separate byte tokens, ids == byte
    // values directly (this fixture's base_tokens list is indexed by raw byte value, see the generator).
    {
        const auto ids = vocab->encode(" world");
        const std::vector<int32_t> expected = {32, 119, 111, 114, 108, 100}; // ' ','w','o','r','l','d'
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == " world");
    }

    // "don't": pretokenizes into ["don", "'t"] (the contraction alternative fires only at the apostrophe,
    // ahead of a bare letter-run match) -- 5 tokens, no merges apply.
    {
        const auto ids = vocab->encode("don't");
        const std::vector<int32_t> expected = {100, 111, 110, 39, 116}; // 'd','o','n','\'','t'
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == "don't");
    }

    // "12": \p{N} has no quantifier in the pretokenizer regex -- each digit is its own chunk, so "12"
    // never has a chance to merge into one piece even though nothing here forbids the *bytes* '1','2'
    // from being adjacent -- this is a deliberate, easy-to-get-wrong detail of the real Qwen2/Qwen3 regex.
    {
        const auto ids = vocab->encode("12");
        const std::vector<int32_t> expected = {49, 50}; // '1','2'
        LOOM_CHECK(ids == expected);
        LOOM_CHECK(vocab->decode(ids) == "12");
    }

    // Non-Latin script (CJK): no merges are defined for it in this tiny fixture, so it necessarily falls
    // back to raw byte-level tokens -- exactly proving that path works (every UTF-8 byte has some base
    // vocab entry) without needing to hand-trace specific ids. Round-trip is the correctness signal.
    {
        const std::string cjk = "\xE4\xB8\xAD\xE6\x96\x87"; // "中文"
        const auto ids = vocab->encode(cjk);
        LOOM_CHECK(ids.size() == 6); // 2 codepoints * 3 UTF-8 bytes each, one token per raw byte
        LOOM_CHECK(vocab->decode(ids) == cjk);
    }

    // NFC fidelity: a decomposed "e" + combining-acute-accent input must encode/decode as the
    // *precomposed* form (encode() NFC-normalizes before tokenizing) -- proves loom::nfc_normalize is
    // actually wired into BpeVocab::encode, not just unit-tested in isolation (test_unicode.cpp).
    {
        const std::string decomposed = "e\xCC\x81";     // U+0065 U+0301
        const std::string precomposed = "\xC3\xA9";      // U+00E9 "é"
        const auto ids = vocab->encode(decomposed);
        LOOM_CHECK(vocab->decode(ids) == precomposed);
        LOOM_CHECK(loom::nfc_normalize(decomposed) == precomposed);
    }

    // --- kGpt2Classic shape ("gpt-2" pre, unbounded digit run + case-sensitive contraction) ---
    {
        const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/bpe_vocab_gpt2_test.gguf";
        auto gpt2_model = loom::GgufModel::load(path, backend.get());
        LOOM_CHECK(gpt2_model != nullptr);
        auto gpt2_vocab = loom::BpeVocab::load(*gpt2_model);
        LOOM_CHECK(gpt2_vocab != nullptr);

        // "12": unbounded `\p{N}+` groups both digits into ONE pretokenizer chunk (unlike qwen2's
        // digit-by-digit chunking above), so the "1 2" merge -- unreachable under qwen2 -- now applies,
        // reducing to the single "12" token (id 260, the 5th extra token after ll/he/hell/hello).
        {
            const auto ids = gpt2_vocab->encode("12");
            LOOM_CHECK((ids == std::vector<int32_t>{260}));
            LOOM_CHECK(gpt2_vocab->decode(ids) == "12");
        }
        // "don'T": kGpt2Classic's contraction alternative is case-SENSITIVE literal text ('t, not (?i:'t))
        // -- the uppercase "'T" does NOT match it (unlike qwen2/llama3's case-insensitive contraction),
        // so it falls through to a lone "'" punctuation chunk, then a separate single-letter "T" chunk,
        // rather than qwen2's single "'T" contraction chunk. No merges apply either way, so this is a
        // round-trip check (chunk boundaries don't cross real vocab merges here) rather than a
        // hand-traced-id difference.
        {
            const auto ids = gpt2_vocab->encode("don'T");
            LOOM_CHECK(gpt2_vocab->decode(ids) == "don'T");
        }
    }

    // --- kWhitespacePunctExclude shape ("poro-chat" pre, excludes a fixed literal punctuation set) ---
    {
        const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/bpe_vocab_poro_test.gguf";
        auto poro_model = loom::GgufModel::load(path, backend.get());
        LOOM_CHECK(poro_model != nullptr);
        auto poro_vocab = loom::BpeVocab::load(*poro_model);
        LOOM_CHECK(poro_vocab != nullptr);

        // "abc,def": ',' is in the shape's literal excluded-punctuation set (unlike qwen2's general
        // \p{L}/\p{N}/\p{P} classification), so it becomes its own single-character chunk between two
        // word chunks -- byte ids for ',' (44) sit standalone between "abc" and "def"'s raw byte ids.
        {
            const auto ids = poro_vocab->encode("abc,def");
            const std::vector<int32_t> expected = {97, 98, 99, 44, 100, 101, 102};
            LOOM_CHECK(ids == expected);
            LOOM_CHECK(poro_vocab->decode(ids) == "abc,def");
        }
        // "hello world": unaffected by the shape difference (no excluded punctuation), still fully
        // reduces "hello" via the same 4 merges -- confirms the vocab/merges are shape-independent.
        {
            const auto ids = poro_vocab->encode("hello world");
            LOOM_CHECK(ids.front() == 259); // "hello" -> single token, same id as the qwen2 fixture
            LOOM_CHECK(poro_vocab->decode(ids) == "hello world");
        }
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
