// Tests loom::ByteVocab (src/core/byte_vocab.cpp) against the small synthetic ByT5-family fixture
// generated by tests/fixtures/make_byte_vocab_gguf.py. Expected ids below were cross-checked against a
// real `transformers.ByT5Tokenizer()` instance (byte b -> id b+3, eos=1 appended, sentinels sequential
// right after the byte range at 259.. by default -- NOT the reversed/from-the-end scheme its own
// docstring describes).

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/byte_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    LOOM_CHECK(model != nullptr);

    auto vocab = loom::ByteVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 3 + 256 + 4); // this fixture's small EXTRA_IDS=4
    LOOM_CHECK(vocab->pad_id() == 0);
    LOOM_CHECK(vocab->eos_id() == 1);
    LOOM_CHECK(vocab->unk_id() == 2);

    // "hi": 'h'=104->107, 'i'=105->108, then eos_id_ (1) appended -- matches the real tokenizer exactly
    // (ByT5Tokenizer().encode("hi") == [107, 108, 1]).
    {
        const auto ids = vocab->encode("hi");
        LOOM_CHECK((ids == std::vector<int32_t>{107, 108, 1}));
        LOOM_CHECK(vocab->decode(ids) == "hi</s>"); // decode does not skip special tokens, like every
                                                     // other loom vocab class's decode()
    }

    // "café": exercises a multi-byte UTF-8 codepoint ('é' = 0xC3 0xA9 = bytes 195,169 -> ids 198,172) --
    // matches the real tokenizer exactly (ByT5Tokenizer().encode("café") == [102,100,105,198,172,1]).
    {
        const auto ids = vocab->encode("caf\xC3\xA9");
        LOOM_CHECK((ids == std::vector<int32_t>{102, 100, 105, 198, 172, 1}));
        LOOM_CHECK(vocab->decode(ids) == "caf\xC3\xA9</s>");
    }

    // Empty input still gets eos-appended (matches build_inputs_with_special_tokens: `X </s>`).
    {
        const auto ids = vocab->encode("");
        LOOM_CHECK((ids == std::vector<int32_t>{1}));
    }

    // Sentinel decode: extra_id_0 is the first id right after the byte range (3+256=259), not the last
    // id in the vocab (contra the upstream docstring's claim -- verified against the real tokenizer).
    {
        const auto ids = std::vector<int32_t>{259, 262, 1}; // <extra_id_0>, <extra_id_3>, </s>
        LOOM_CHECK(vocab->decode(ids) == "<extra_id_0><extra_id_3></s>");
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
