// Tests loom::PhonemeVocab (src/core/phoneme_vocab.cpp) against the synthetic twelve-symbol fixtures
// generated by tests/fixtures/make_phoneme_vocab_gguf.py -- the longest-match scan, the per-checkpoint
// assembly, the -1 sentinel and the skip-don't-raise rule for a symbol outside the table.
//
// The class shipped with the export half of Task #79 and had NO test in this tree at all, while every
// sibling vocabulary here has one. That mattered more than the usual gap: the four TTS families it
// serves are checked end-to-end by gate tests that drive them with synthetic ids, so nothing in the
// suite ever went through this table, and a regression in the scan would have shown a green run and
// audio that was subtly not the sentence (Retro-006).
//
// It is deliberately hermetic. Whether piper's real 159 symbols round-trip is a property of the EXPORT,
// which loom-exporter's own tests/ci/test_tts_text_door.py already holds; what is here is the behaviour
// that is the same whatever table is loaded.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

namespace {

// The fixture's ids, by name rather than by number at each use site.
constexpr int32_t kBlank = 0, kBos = 1, kEos = 2, kSpace = 3;
constexpr int32_t kA = 4, kSmallI = 5, kAI = 6, kT = 7, kEsh = 8, kTEsh = 9, kUnused = 10, kH = 11;

} // namespace

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    auto load = [&backend](const char* name) {
        auto model = loom::GgufModel::load(std::string(LOOM_TEST_FIXTURE_DIR) + "/" + name, backend.get());
        LOOM_CHECK(model != nullptr);
        return model;
    };

    auto model = load("phoneme_vocab_test.gguf");
    auto vocab = loom::PhonemeVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);

    LOOM_CHECK(vocab->size() == 12);

    // Read from the file, not assumed: the assembly is a property of the checkpoint, which is the whole
    // reason it is four KVs rather than four constants in this class.
    LOOM_CHECK(vocab->bos_id() == kBos);
    LOOM_CHECK(vocab->eos_id() == kEos);
    LOOM_CHECK(vocab->blank_id() == kBlank);
    LOOM_CHECK(vocab->interleave_blank());

    // Piper's build: a blank after every phoneme, none right after BOS, EOS last.
    LOOM_CHECK(vocab->encode("a") == std::vector<int32_t>({kBos, kA, kBlank, kEos}));
    LOOM_CHECK(vocab->encode("ah") == std::vector<int32_t>({kBos, kA, kBlank, kH, kBlank, kEos}));

    // LONGEST MATCH, the property the whole scan exists for. "aɪ" is one symbol the table holds and also
    // two symbols it holds separately; a shortest-first walk returns the second reading, which is a
    // sequence the model was never trained on rather than a near miss.
    LOOM_CHECK(vocab->encode("aɪ") == std::vector<int32_t>({kBos, kAI, kBlank, kEos}));
    LOOM_CHECK(vocab->encode("aɪ") != std::vector<int32_t>({kBos, kA, kBlank, kSmallI, kBlank, kEos}));

    // Three codepoints, and its first codepoint is a symbol of its own -- so this fails for a scan whose
    // upper bound is a codepoint rather than the longest entry in the table.
    LOOM_CHECK(vocab->encode("t͡ʃ") == std::vector<int32_t>({kBos, kTEsh, kBlank, kEos}));
    LOOM_CHECK(vocab->encode("tʃ") == std::vector<int32_t>({kBos, kT, kBlank, kEsh, kBlank, kEos}));

    // A symbol outside the table is SKIPPED, not raised on: a rule-based G2P emits a superset of what any
    // one checkpoint was trained on, so refusing the utterance over one diacritic would fail every long
    // sentence. What a caller gets instead is the count.
    {
        size_t unknown = 0;
        // "漢" is one codepoint in three bytes and "b" is one in one: two symbols dropped, not four. A
        // per-byte advance would report the multi-byte one three times AND resume mid-sequence, where
        // nothing in the table can match.
        const auto ids = vocab->encode("a漢b", &unknown);
        LOOM_CHECK(unknown == 2);
        LOOM_CHECK(ids == std::vector<int32_t>({kBos, kA, kBlank, kEos}));

        size_t none_dropped = 1;  // written even when nothing is dropped, so a caller can trust the zero
        vocab->encode("ah", &none_dropped);
        LOOM_CHECK(none_dropped == 0);

        // Every symbol dropped still assembles, because the assembly is the checkpoint's and not the
        // text's. It is a silent utterance rather than an error, which is why the count is the door.
        size_t all_dropped = 0;
        LOOM_CHECK(vocab->encode("漢字", &all_dropped) == std::vector<int32_t>({kBos, kEos}));
        LOOM_CHECK(all_dropped == 2);
    }

    // decode() drops the assembly ids and returns only what the model was asked to SAY -- the round trip
    // a caller inspects. Printing the interleaved blank back would put a symbol between every phoneme.
    LOOM_CHECK(vocab->decode(vocab->encode("a h")) == "a h");
    LOOM_CHECK(vocab->decode(vocab->encode("t͡ʃaɪ")) == "t͡ʃaɪ");
    LOOM_CHECK(vocab->decode({}).empty());

    // An id no symbol occupies is "" rather than out-of-bounds, in both directions.
    LOOM_CHECK(vocab->piece(kH) == "h");
    LOOM_CHECK(vocab->piece(-1).empty());
    LOOM_CHECK(vocab->piece(12).empty());
    // A gap carries a NAME, not the empty string: every gap sharing "" would make one lookup key claim
    // all of them, and this table is not dense in general.
    LOOM_CHECK(vocab->piece(kUnused) == "<unused10>");

    // The bare shape: bos only, `eos_id`/`blank_id` the -1 sentinel, no interleave. This is StyleTTS2's
    // real declaration and the one a "-1 is just an id" reading breaks on -- appending it reaches the
    // engine as an out-of-range GET_ROWS rather than as anything a caller could diagnose.
    {
        auto bare_model = load("phoneme_vocab_bare.gguf");
        auto bare = loom::PhonemeVocab::load(*bare_model);
        LOOM_CHECK(bare != nullptr);

        // Id 0 is `<blank>` in the table and the BOS in this file's assembly -- which is StyleTTS2's own
        // arrangement, where the symbol at 0 is a pad the export also names as the wrap.
        constexpr int32_t kBareBos = 0;
        LOOM_CHECK(bare->bos_id() == kBareBos);
        LOOM_CHECK(bare->eos_id() == -1);
        LOOM_CHECK(bare->blank_id() == -1);
        LOOM_CHECK(!bare->interleave_blank());
        LOOM_CHECK(bare->encode("ah") == std::vector<int32_t>({kBareBos, kA, kH}));
        LOOM_CHECK(bare->decode(bare->encode("ah")) == "ah");

        // The duplicate: "a" is at id 4 and again at id 12. The LOWER id wins, so which one a host gets
        // is decided here rather than by the order the array happened to be written in.
        LOOM_CHECK(bare->size() == 13);
        LOOM_CHECK(bare->piece(12) == "a");
        LOOM_CHECK(bare->encode("a") == std::vector<int32_t>({kBareBos, kA}));
    }

    // The tag with no table is MALFORMED rather than merely new, and is the one input this loader is
    // supposed to refuse -- absence of the tag is the answer for every other model in the tree, absence
    // of the data under a present tag is a broken file.
    {
        auto broken = load("phoneme_vocab_no_tokens.gguf");
        bool threw = false;
        try {
            loom::PhonemeVocab::load(*broken);
        } catch (const loom::LoadError&) {
            threw = true;
        }
        LOOM_CHECK(threw);
    }

    // A GGUF with some OTHER tokenizer family must not be claimed by this class -- the dispatch every
    // host does is by tag, and load() returning non-null for a "byt5" file would silently win it.
    {
        auto other = load("byte_vocab_test.gguf");
        LOOM_CHECK(loom::PhonemeVocab::load(*other) == nullptr);
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
