// Tests loom::SopranoVocab (src/core/soprano_vocab.cpp) against the fixture generated by
// tests/fixtures/make_soprano_vocab_gguf.py: the reference's own rule tables, a six-codepoint
// `unidecode` table and a character vocabulary with two merges.
//
// **The measured claim is that `encode` IS the reference's text path** --
// `SopranoTTS._preprocess_text` (clean_text, the sentence split, the short-sentence merge, the prompt)
// and then the real tokenizer -- and that comparison lives where the reference can run: 20,000/20,000
// texts over ten classes (numbers, abbreviations, symbols, links and brackets, Unicode, long multi-
// sentence prose, newlines, punctuation, quotes, character soup), two seeds, with the reference's
// crashes compared as refusals. Four sabotaged references go red: numbers not normalised (883/2000
// differ), no short-sentence merge (891), `unidecode` skipped (494), and a sentence budget of 299
// characters instead of 300 (13). Each expectation below is the reference's own output.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

#include <string>
#include <vector>

using Ids = std::vector<int32_t>;
using Strings = std::vector<std::string>;

namespace {

constexpr int32_t kText = 1, kStart = 2, kStop = 3;

bool throws_on(const loom::SopranoVocab& vocab, const std::string& text) {
    try {
        vocab.encode(text);
    } catch (const loom::Error&) {
        return true;
    }
    return false;
}

} // namespace

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);
    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/soprano_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    auto vocab = loom::SopranoVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->stop_id() == kStop);

    // --- clean_text, one rule family per line ---
    auto clean = [&](const std::string& t) { return vocab->clean_text(t); };
    LOOM_CHECK(clean("#1 fan") == "number one fan.");
    LOOM_CHECK(clean("100k views") == "one hundred thousand views.");
    LOOM_CHECK(clean("1,000,000") == "one million.");
    LOOM_CHECK(clean("1/1/2025") == "one dash one dash twenty twenty-five.");
    LOOM_CHECK(clean("(555) 123-4567") == "five five five, one two three, four five six seven.");
    LOOM_CHECK(clean("8:00") == "eight o'clock.");
    LOOM_CHECK(clean("13:00") == "thirteen minutes.");
    LOOM_CHECK(clean("8:05") == "eight oh five.");
    // `_expand_time`'s set literal: the minutes come out as `{'15'}`, and the braces are dropped later.
    LOOM_CHECK(clean("01:15:30") == "one, 'fifteen', thirty.");
    LOOM_CHECK(clean("00:01:10") == "one ten.");
    // `unidecode` runs first, so a pound sign is "PS" before `_pounds_re` can see it.
    LOOM_CHECK(clean("\xc2\xa3" "20") == "ps twenty.");
    LOOM_CHECK(clean("$2.47") == "two dollars, forty-seven cents.");
    LOOM_CHECK(clean("$1") == "one dollar.");
    LOOM_CHECK(clean("$0.01") == "one cent.");
    LOOM_CHECK(clean("2.47") == "two point four seven.");
    LOOM_CHECK(clean("3 * 4") == "three times four.");
    LOOM_CHECK(clean("7/8") == "seven over eight.");
    LOOM_CHECK(clean("1+2") == "one plus two.");
    LOOM_CHECK(clean("6 - 7") == "six minus seven.");
    LOOM_CHECK(clean("1/2/3") == "one over two over three.");
    LOOM_CHECK(clean("21st") == "twenty-first.");
    LOOM_CHECK(clean("x1") == "x one.");
    LOOM_CHECK(clean("Mr. Smith") == "mister smith.");
    LOOM_CHECK(clean("API") == "a p i.");
    LOOM_CHECK(clean("TPUs") == "tpu's.");
    LOOM_CHECK(clean("LMDeploy") == "l m deploy.");
    LOOM_CHECK(clean("https://x") == "h t t p s colon slash slash x.");
    LOOM_CHECK(clean("a - b") == "a, b.");
    LOOM_CHECK(clean("U.S") == "u dot s.");
    LOOM_CHECK(clean("(an aside) here") == ", an aside, here.");
    LOOM_CHECK(clean("5% & 6") == "five percent and six.");
    // Numbers run before symbols, so "<3" is "<three" by the time `(^| )<3` could see it.
    LOOM_CHECK(clean("<3 you") == "less than three you.");
    LOOM_CHECK(clean("caf\xc3\xa9 \xe2\x80\x94 na\xc3\xafve \xe2\x80\x9cquoted\xe2\x80\x9d") == "cafe, naive quoted.");
    LOOM_CHECK(clean("Hmmmm...!!") == "hmm...!");
    LOOM_CHECK(clean("line one\nline two") == "line one. line two.");
    LOOM_CHECK(clean("Wait!!! Really??") == "wait! really?");

    // --- _expand_number and inflect ---
    LOOM_CHECK(vocab->expand_number("1990") == "nineteen ninety");
    LOOM_CHECK(vocab->expand_number("2000") == "two thousand");
    LOOM_CHECK(vocab->expand_number("2005") == "two thousand five");
    LOOM_CHECK(vocab->expand_number("1900") == "nineteen hundred");
    LOOM_CHECK(vocab->expand_number("1001") == "ten oh one");
    LOOM_CHECK(vocab->expand_number("3456") == "three thousand, four hundred fifty-six");
    LOOM_CHECK(vocab->expand_number("0100") == "one hundred");
    LOOM_CHECK(vocab->expand_number("0") == "zero");
    LOOM_CHECK(vocab->number_to_words("12", true) == "twelfth");
    LOOM_CHECK(vocab->number_to_words("20", true) == "twentieth");
    LOOM_CHECK(vocab->number_to_words("100", true) == "one hundredth");
    // 37 digits need a twelfth scale word, which inflect does not have (NumOutOfRangeError).
    LOOM_CHECK(throws_on(*vocab, std::string(37, '1')));
    LOOM_CHECK(!throws_on(*vocab, std::string(36, '1')));
    // `int(",5")` raises in `_expand_dollars`.
    LOOM_CHECK(throws_on(*vocab, "$,5"));

    // --- the split and the merge ---
    // Every short sentence joins a neighbour, so this is one generation.
    LOOM_CHECK((vocab->sentences("Hi. This is a much longer sentence than thirty characters. Ok. Bye now!") ==
                Strings{"hi. this is a much longer sentence than thirty characters. ok. bye now!"}));
    LOOM_CHECK((vocab->sentences("He said \"Go now. Please.\" Then left. And that was the end of the story "
                                 "for him.") ==
                Strings{"he said go now. please. then left.", "and that was the end of the story for him."}));
    LOOM_CHECK(throws_on(*vocab, ""));
    LOOM_CHECK(throws_on(*vocab, " ... "));

    // --- the tokenizer and the prompt ---
    // A character table: ' ' is 4, then "!$%&'*,-." (5..13), digits 14..23, '?' 24, a..z 25..50, then
    // "th" 51 and "the" 52.
    auto letter = [](char c) { return static_cast<int32_t>(25 + (c - 'a')); };
    LOOM_CHECK((vocab->tokenize("the cat.") == Ids{52, 4, letter('c'), letter('a'), letter('t'), 13}));
    // Every digit is its own pre-token; an unknown character is [UNK].
    LOOM_CHECK((vocab->tokenize("a12") == Ids{letter('a'), 15, 16}));
    LOOM_CHECK((vocab->tokenize("a#") == Ids{letter('a'), 0}));
    LOOM_CHECK((vocab->encode("The cat. A dog walked far away from home.") ==
                [&] {
                    Ids ids{kStop, kText};
                    const Ids body = vocab->tokenize("the cat. a dog walked far away from home.");
                    ids.insert(ids.end(), body.begin(), body.end());
                    ids.push_back(kStart);
                    return ids;
                }()));

    // Another family's file is declined, not misread.
    {
        const std::string ctc = std::string(LOOM_TEST_FIXTURE_DIR) + "/ctc_vocab_test.gguf";
        auto other = loom::GgufModel::load(ctc, backend.get());
        LOOM_CHECK(loom::SopranoVocab::load(*other) == nullptr);
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
