// Tests loom::VoxCpmVocab (src/core/voxcpm_vocab.cpp) against the synthetic fixture generated by
// tests/fixtures/make_voxcpm_vocab_gguf.py.
//
// **The measured claim is that `encode` IS the reference's text path** -- `VoxCPM._generate`'s
// whitespace preparation, `LlamaTokenizerFast.tokenize`, then `mask_multichar_chinese_tokens` -- and
// that comparison lives where the reference can run: against the real table, 4992/4992 texts over ten
// input classes (prose, voice-design prefixes, Chinese, mixed scripts, other scripts, byte-fallback
// characters, whitespace edges, numbers, typed special tokens, punctuation soup); a sabotaged file
// that keeps one split entry differs on 243 of 999. What belongs here is each step, one case apiece, on
// a table small enough that every id is derivable by hand.

#include "test_util.h"

#include "loom/loom.h"

#include "cpu_backend.h"

#include <string>
#include <vector>

using Ids = std::vector<int32_t>;

namespace {

// The fixture's ids: 0-2 the added tokens, 3-258 the byte pieces, then its pieces in order (259 `▁`,
// 260-262 `H` `i` `Hi`, 263 `▁Hi`, 264-267 `a` `b` `ab` `ba`, 268-271 the Chinese ones).
constexpr int32_t kUnk = 0, kBos = 1, kAudioStart = 2, kSpace = 259, kSpaceHi = 263, ka = 264, kb = 265,
                  kab = 266, kNi = 268, kHao = 269;
constexpr int32_t byte_id(int b) { return 3 + b; }

} // namespace

int main() {
    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);
    const std::string path = std::string(LOOM_TEST_FIXTURE_DIR) + "/voxcpm_vocab_test.gguf";
    auto model = loom::GgufModel::load(path, backend.get());
    auto vocab = loom::VoxCpmVocab::load(*model);
    LOOM_CHECK(vocab != nullptr);
    LOOM_CHECK(vocab->size() == 272);

    // --- the preparation: every whitespace run is ONE space, and nothing is stripped. ---
    LOOM_CHECK(vocab->normalize("a\n\t b") == "a b");
    LOOM_CHECK(vocab->normalize("  a  ") == " a ");
    // U+3000 is `str.isspace()`, so the reference's `\s` takes it too.
    LOOM_CHECK(vocab->normalize("a\xe3\x80\x80" "b") == "a b");

    // --- the normalizer and the merges: `▁` prepended, spaces as `▁`, lowest rank first. ---
    // "Hi" -> ▁ H i -> ▁ Hi (rank 0) -> ▁Hi (rank 1). No BOS: the reference calls `tokenize`.
    LOOM_CHECK((vocab->encode("Hi") == Ids{kSpaceHi}));
    // "aba": `a b` (rank 2) outranks `b a` (rank 3), so the result is `ab a`, not `a ba`.
    LOOM_CHECK((vocab->encode("aba") == Ids{kSpace, kab, ka}));
    // "bab": `b a` sits LEFT of `a b`, and `a b` still goes first, because rank beats position -- `b ab`.
    LOOM_CHECK((vocab->encode("bab") == Ids{kSpace, kb, kab}));
    // A space inside the text is a `▁` symbol like any other.
    LOOM_CHECK((vocab->encode("Hi Hi") == Ids{kSpaceHi, kSpaceHi}));

    // --- byte fallback: a character the table lacks is its UTF-8 bytes, and never merges. ---
    size_t fallback = 0;
    LOOM_CHECK((vocab->encode("a\xc3\xa9", &fallback) == Ids{kSpace, ka, byte_id(0xC3), byte_id(0xA9)}));
    LOOM_CHECK(fallback == 1);

    // --- the split: a multi-character Chinese piece becomes its characters, `▁` dropped. ---
    // "你好" -> ▁ 你 好 -> ▁ 你好 -> ▁你好 -> split -> 你 好. The `▁` went with the piece.
    LOOM_CHECK((vocab->encode("\xe4\xbd\xa0\xe5\xa5\xbd") == Ids{kNi, kHao}));

    // --- added tokens: matched literally BEFORE the normalizer, which then runs per segment. ---
    // "<s>Hi" -> <s> | "Hi" -> the segment gets its own `▁`.
    LOOM_CHECK((vocab->encode("<s>Hi") == Ids{kBos, kSpaceHi}));
    LOOM_CHECK((vocab->encode("Hi<|audio_start|>") == Ids{kSpaceHi, kAudioStart}));
    // A lone added token leaves no segment to normalize: no `▁` appears.
    LOOM_CHECK((vocab->encode("<unk>") == Ids{kUnk}));

    // --- decode: `▁` back to a space, bytes re-assembled, the prepended space dropped once. ---
    LOOM_CHECK(vocab->decode({kSpaceHi, kSpace, kab}) == "Hi ab");
    LOOM_CHECK(vocab->decode({kSpace, ka, byte_id(0xC3), byte_id(0xA9)}) == "a\xc3\xa9");

    // --- another family's file is not this one's. ---
    const std::string ctc_path = std::string(LOOM_TEST_FIXTURE_DIR) + "/ctc_vocab_test.gguf";
    auto ctc = loom::GgufModel::load(ctc_path, backend.get());
    LOOM_CHECK(loom::VoxCpmVocab::load(*ctc) == nullptr);

    LOOM_TEST_REPORT_AND_RETURN();
}
