// Tests loom::SupertonicTextVectorizer (src/core/supertonic_text_vectorizer.cpp) against the real
// SupertonicTTS v2 `unicode_indexer.json` asset (converted via
// tools/convert_supertonic/convert_supertonic_text_vectorizer.py -- same "reference-only repo, real
// asset" convention as every other test_e2e_supertonic_*.cpp, see LOOM_SUPERTONIC_TEXT_VECTORIZER_GGUF
// below).
//
// Expected id sequences were generated by running the REAL Python `TextVectorizer` directly against
// supertonic-tts's own checkout:
//   python3 -c "import sys; sys.path.insert(0,'src'); \
//       from supertonic_tts.models.modules.text_vectorizer import TextVectorizer; \
//       print(TextVectorizer().tokenize_str('<text>', '<lang>', return_tensor=False))"

#include "test_util.h"
#include "fixtures.h"

#include "loom/loom.h"

#include "cpu_backend.h"

#include <cstdlib>
#include <sys/stat.h>

namespace {

constexpr int kSkipReturnCode = 77;

bool path_exists(const std::string& path) {
    struct stat st{};
    return ::stat(path.c_str(), &st) == 0;
}

} // namespace

int main() {
    const char* gguf_env = loom_test::fixture_env("LOOM_SUPERTONIC_TEXT_VECTORIZER_GGUF");
    if (gguf_env == nullptr || !path_exists(gguf_env)) {
        std::fprintf(stderr,
                      "skipping: set LOOM_SUPERTONIC_TEXT_VECTORIZER_GGUF to a real GGUF produced by "
                      "tools/convert_supertonic/convert_supertonic_text_vectorizer.py to run this check\n");
        return kSkipReturnCode;
    }

    ggml_backend_ptr backend(loom_test::cpu_backend());
    LOOM_CHECK(backend != nullptr);

    auto model = loom::GgufModel::load(gguf_env, backend.get());
    LOOM_CHECK(model != nullptr);

    auto vec = loom::SupertonicTextVectorizer::load(*model);
    LOOM_CHECK(vec != nullptr);
    LOOM_CHECK(vec->vocab_size() == 65536); // real unicode_indexer.json is a flat BMP-sized array
    // ...of which only 162 entries are mapped, onto ids 0..161. The real `nn.Embedding` has 163 rows;
    // the spare one is headroom no codepoint reaches (see supertonic_common.py), so it is not counted.
    LOOM_CHECK(vec->n_tokens() == 162);

    {
        const auto ids = vec->tokenize("hello world", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 63, 60, 67, 67, 70, 0, 78, 70, 73, 67, 59,
                                                13, 27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Exercises the punctuation-spacing fix (" ," and " !" both collapse) and case (upper+lower).
        const auto ids = vec->tokenize("Hello, World!", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 37, 60, 67, 67, 70, 11, 0, 52, 70, 73, 67,
                                                59, 1, 27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Exercises the apostrophe/single-quote replacement + spacing fix.
        const auto ids = vec->tokenize("it's a test", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 64, 75, 6, 74, 0, 56, 0, 75, 60, 74, 75, 13,
                                                27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Exercises NFD-decomposition + combining-acute-accent handling ("é" -> e + combining acute,
        // matching the vocab's own combining-mark entries) with a non-"en" lang tag.
        const auto ids = vec->tokenize("caf\xC3\xA9", "fr"); // "café"
        const std::vector<int32_t> expected = {27, 61, 73, 28, 58, 56, 61, 60, 90, 13, 27, 14, 61, 73, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Exercises the expression-replacement step ("e.g.," -> "for example, ", "@" -> " at ").
        const auto ids = vec->tokenize("e.g., this @ that", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 61, 70, 73, 0, 60, 79, 56, 68, 71, 67, 60,
                                                11, 0, 75, 63, 64, 74, 0, 56, 75, 0, 75, 63, 56, 75, 13,
                                                27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Exercises whitespace collapsing (leading/trailing/internal runs).
        const auto ids = vec->tokenize("  multiple   spaces  ", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 68, 76, 67, 75, 64, 71, 67, 60, 0, 74, 71,
                                                56, 58, 60, 74, 13, 27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Exercises quote-deduplication (`""..""` collapses to a single `"` on each side).
        const auto ids = vec->tokenize("quotes \"\"test\"\"", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 72, 76, 70, 75, 60, 74, 0, 2, 75, 60, 74,
                                                75, 2, 27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Empty input still gets a trailing "." inserted and lang-tag-wrapped.
        const auto ids = vec->tokenize("", "en");
        const std::vector<int32_t> expected = {27, 60, 69, 28, 13, 27, 14, 60, 69, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // Korean: NFD-decomposes precomposed Hangul syllables into individual jamo (choseong/jungseong/
        // jongseong), matching the vocab's own Hangul-Jamo-block entries -- "안녕" (2 syllables) -> 6 jamo.
        const auto ids = vec->tokenize("\xEC\x95\x88\xEB\x85\x95", "ko"); // "안녕"
        const std::vector<int32_t> expected = {27, 66, 70, 28, 106, 114, 138, 97, 120, 154, 13, 27, 14,
                                                66, 70, 28};
        LOOM_CHECK(ids == expected);
    }
    {
        // An omitted lang uses the file's own declared default. A GGUF written before
        // "tokenizer.ggml.supertonic.default_lang" existed carries no such KV and falls back to "en",
        // which is why this asserts the RESULT rather than the KV: both spellings must reach the same
        // ids the explicit "en" cases above produce.
        LOOM_CHECK(vec->tokenize("hello world") == vec->tokenize("hello world", vec->default_lang()));
        if (vec->default_lang() == "en") {
            const std::vector<int32_t> expected = {27, 60, 69, 28, 63, 60, 67, 67, 70, 0, 78, 70, 73, 67,
                                                    59, 13, 27, 14, 60, 69, 28};
            LOOM_CHECK(vec->tokenize("hello world") == expected);
        }
    }
    {
        // The real asset is injective (162 codepoints -> 162 distinct ids), so the ids round-trip back to
        // the PREPROCESSED text -- wrap, inserted period and all. Checking the whole wrapped string rather
        // than "hello world" is the point: detokenize inverts the table, not the pipeline.
        LOOM_CHECK(vec->detokenize(vec->tokenize("hello world", "en")) == "<en>hello world.</en>");
        // Id 162 is the spare embedding row no codepoint maps to; it drops, like an unsupported codepoint.
        LOOM_CHECK(vec->detokenize({60, 162, 69}) == "en");
    }

    LOOM_TEST_REPORT_AND_RETURN();
}
