-- Lua orchestration for the MIL-traced StyleTTS2 export (export_styletts2_mil.py), analogous to
-- styletts2_driver.lua (the hand-built-topology driver) but wiring in the THREE machine-traced
-- topologies export_styletts2_mil.py produces ("albert", "decoder_vocoder", "diffusion") in place of
-- FIVE of styletts2_driver.lua's own bespoke topology calls ("albert" alone, and
-- "decoder_core"+"sinegen"+"stft_forward"+"generator" respectively -- "diffusion" keeps its own name but
-- is now a MIL trace of the REAL Transformer1d.run() instead of a hand-derived topology). Everything else
-- (bert_encoder, DurationEncoder/predictor.lstm/duration_proj, TextEncoder's BiLSTM, F0Ntrain) stays on
-- the EXISTING bespoke, hand-built LSTM-bound topologies -- ggml has no native LSTM op, same deliberate
-- scoping exclusion Kokoro's own MIL export already established (see kokoro_driver/'s own header).
--
-- What's different from styletts2_driver.lua, and why this isn't just that file with three calls swapped:
--   - No `positions`/`attn_mask` inputs to "albert" at all: the MIL-traced CustomAlbert computes position
--     ids (from a registered buffer, sliced dynamically) and the additive attention mask (always
--     all-zeros -- real usage is always a single, unpadded utterance) IN-GRAPH now, not host-side --
--     identical reasoning to kokoro_driver/'s own "albert_bert_encoder" phase.
--   - "albert" returns TIME-MAJOR (T,768) (`flat[t*768+c]`, this file's own "row_major" convention) instead
--     of styletts2_driver.lua's own Layout-B convention -- a deliberate choice in export_styletts2_mil.py's
--     own AlbertWrapper to avoid returning a bare `.transpose()`/permute as a traced graph's own output
--     (the exact bug export_vits_mil.py's own StatsWrapper already found and worked around). Byte-identical
--     to ne=[768,T] either way (row-major IS Layout B, see convert_styletts2_diffusion.py's own axis-
--     convention comment) -- `bert_out` feeds straight into both "bert_encoder" (unchanged, Layout-A-typed
--     input `x`) and "diffusion"'s own `embedding` input with NO reordering needed.
--   - "diffusion" no longer takes an `attn_mask` input: the REAL Transformer1d has no masking at all
--     (plain, un-masked self-attention -- confirmed reading Modules/diffusion/modules.py directly, no
--     `attn_mask`/`rel_pos` argument anywhere in AttentionBase.forward). The OLD bespoke topology declared
--     one anyway only because loom's hand-authored ATTENTION op needed some mask tensor as an API
--     formality (always zero-filled) -- the traced version's manual einsum-free (see export_styletts2_mil
--     .py's own AttentionBase.forward patch) softmax attention has no such requirement.
--   - "decoder_vocoder" replaces FOUR bespoke calls (decoder_core, sinegen, stft_forward, generator) with
--     ONE: it takes asr/f0_curve/n_curve/s/rand_ini/noise_in/wsum directly and returns the finished
--     WAVEFORM -- no host-side har (STFT mag/phase) assembly or Generator-input wiring needed at all, only
--     the SAME rand_ini/noise/wsum host-precomputation styletts2_driver.lua's own generator call already
--     required (F0Ntrain and everything upstream of the decoder is IDENTICAL to styletts2_driver.lua --
--     still bespoke/LSTM-bound, unchanged). Matches kokoro_driver/'s own identical simplification,
--     input-for-input (StyleTTS2's decoder/generator/sinegen ARE Kokoro's own istftnet classes, just
--     StyleTTS2's own checkpoint weights -- see export_styletts2_mil.py's own module docstring).
--
-- Expects every topology pre-registered by the host from ONE GgufModel over styletts2_mil.gguf --
-- none uses a KvCache. It used to take two, because this export was partial and the LSTM-bound half
-- came from convert_styletts2_reused.py's per-topology GGUFs alongside; P4.0.7 traced those from the
-- real checkpoint too, so the artifact is self-contained now.
--
-- inputs: input_ids (int array, real StyleTTS2 wraps with a SINGLE LEADING 0 token only -- caller's
-- responsibility), diffusion_steps (int, ADPM2Sampler's own num_steps), seed (int, seeds loom.seed_rng --
-- BOTH the diffusion sampler's own noise draws AND SineGen's rand_ini/noise draws are drawn from this one
-- shared stream, in that order, matching styletts2_driver.lua's own draw order EXACTLY so the two drivers
-- stay bit-reproducible against each other given the same seed).
--
-- style_dim, d_model, hidden_per_dir, harmonic_num, upsample_scale, gen_istft_n_fft, gen_istft_hop,
-- sigma_min, sigma_max, rho and sigma_data used to be inputs too. They are the eleven UPPER_CASE
-- locals below now (P4.0.8's first follow-up): three read off the real TextEncoder/ProsodyPredictor,
-- four the istftnet geometry the decoder_vocoder graph was traced with, three StyleTTS2's own
-- "empirical" Karras schedule, and SIGMA_DATA out of the checkpoint's own config.yml, where
-- `estimate_sigma_data: True` makes it a per-training-run statistic rather than a constant.
-- diffusion_steps stays an input, because it is the one the real repo's inference entry point exposes.
-- The GGUF also declares STYLE_DIM as the `loom.style_dim` hparam, for a host that needs the style
-- vector's own width.
--
-- Returns: the raw waveform (flat f32 array), same convention as styletts2_driver.lua's own return.
