-- Lua orchestration for the MIL-traced Kokoro export (export_kokoro_mil.py), analogous to
-- kokoro_driver.lua (the hand-built-topology driver) but wiring in the TWO machine-traced combined
-- topologies export_kokoro_mil.py produces ("albert_bert_encoder", "decoder_vocoder") in place of FOUR
-- of kokoro_driver.lua's own bespoke topology calls each ("albert"+"bert_encoder", and
-- "decoder_core"+"sinegen"+"stft_forward"+"generator" respectively). Kokoro leans heavily on
-- `torch.nn.LSTM` (ggml has no native LSTM op) -- deliberate scoping decision (see BACKLOG.md): the
-- LSTM-bound pieces (TextEncoder's BiLSTM, DurationEncoder, predictor.lstm, F0Ntrain's shared LSTM)
-- REMAIN the existing bespoke, hand-built topologies (unchanged from kokoro_driver.lua), loaded from the
-- separate bespoke kokoro.gguf (tools/convert_kokoro/convert_kokoro_lua_all.py) alongside this driver's
-- own kokoro_mil.gguf -- register_module doesn't care which GgufModel a topology's weights live in, only
-- that all of them share one LoomLuaBridge instance.
--
-- What's different from kokoro_driver.lua, and why this isn't just that file with two calls swapped:
--   - No `positions`/`attn_mask` inputs to "albert_bert_encoder" at all: the MIL-traced CustomAlbert
--     computes position ids (from a registered buffer, sliced dynamically) and the additive attention
--     mask (always all-zeros -- real usage is always a single, unpadded utterance, same convention
--     convert_kokoro_albert.py's own bespoke topology already established) IN-GRAPH now, not host-side.
--   - "albert_bert_encoder" returns TIME-MAJOR (T,512) (`flat[t*512+c]`, this file's own "row_major"
--     convention below) instead of kokoro_driver.lua's "d_en_flat" Layout-A convention (`flat[c*T+t]`) --
--     a deliberate choice in export_kokoro_mil.py's own AlbertBertEncoderWrapper to avoid returning a
--     bare `.transpose()` as a traced graph's own output (a live non-contiguous view read in PRE-permute
--     order by this project's raw contiguous-byte-copy GGUF/weight extraction -- the exact bug
--     export_vits_mil.py's own StatsWrapper already found and worked around for VITS's `stats` output).
--     `from_row_major` converts straight to the per-timestep rows DurationEncoder's own "x" construction
--     needs, actually SIMPLER than kokoro_driver.lua's own manual c*T+t indexing loop.
--   - "decoder_vocoder" replaces FOUR bespoke calls (decoder_core, sinegen, stft_forward, generator) with
--     ONE: it takes asr/F0_curve/N_curve/style/rand_ini/noise_in/wsum directly and returns the finished
--     WAVEFORM -- no host-side har (STFT mag/phase) assembly or Generator-input wiring needed at all,
--     only the SAME rand_ini/noise/wsum host-precomputation kokoro_driver.lua's own generator call
--     already required (F0Ntrain and everything upstream of the decoder is IDENTICAL to kokoro_driver.lua
--     -- still bespoke/LSTM-bound, unchanged).
--
-- Expects topologies pre-registered by the host, from TWO GgufModel instances sharing one bridge:
--   kokoro_mil.gguf: "albert_bert_encoder", "decoder_vocoder"
--   kokoro.gguf (bespoke): "text_encoder_cnn", "text_encoder_lstm_{h,c}_{fwd,bwd}",
--     "duration_lstm_{0,1,2}_{h,c}_{fwd,bwd}", "duration_adaln_{0,1,2}", "top_lstm_{h,c}_{fwd,bwd}",
--     "duration_proj", "f0n_shared_lstm_{h,c}_{fwd,bwd}", "f0n_f0_block{0,1,2}", "f0n_n_block{0,1,2}",
--     "f0n_f0_proj", "f0n_n_proj" -- none use a KvCache.
--
-- inputs: input_ids (int array, CustomAlbert's own vocabulary, caller wraps with leading/trailing 0 per
-- real KModel.forward's own convention), ref_s (256 floats: [1..style_dim]=decoder style,
-- [style_dim+1..2*style_dim]=predictor style), speed (float), seed (int, seeds loom.seed_rng --
-- SineGen's rand_ini/noise draws are the only stochastic step in this whole pipeline, SAME draw order as
-- kokoro_driver.lua: uniform first then gaussian, against the ONE shared rng_ stream), plus the real
-- model constants style_dim, d_model, hidden_per_dir, harmonic_num, upsample_scale, gen_istft_n_fft,
-- gen_istft_hop (KokoroConfig's own real defaults).
--
-- Returns: the raw waveform (flat f32 array), same convention as kokoro_driver.lua's own return.
