-- Lua orchestration for the MIL-traced Kokoro export (export_kokoro_mil.py), analogous to
-- kokoro_driver.lua (the hand-built-topology driver) but wiring in the TWO machine-traced combined
-- topologies export_kokoro_mil.py produces ("albert_bert_encoder", "decoder_vocoder") in place of FOUR
-- of kokoro_driver.lua's own bespoke topology calls each ("albert"+"bert_encoder", and
-- "decoder_core"+"sinegen"+"stft_forward"+"generator" respectively). Kokoro leans heavily on
-- `torch.nn.LSTM` (ggml has no native LSTM op), which is why the LSTM-bound pieces (TextEncoder's
-- BiLSTM, DurationEncoder, predictor.lstm, F0Ntrain's shared LSTM) are per-timestep CELL topologies
-- driven by a host loop rather than one graph -- `RecurrentPhase` traces them from the real
-- checkpoint, so they live in this same file (P4.0.7). They were borrowed from the pre-MIL
-- kokoro.gguf until then.
--
-- What's different from kokoro_driver.lua, and why this isn't just that file with two calls swapped:
--   - No `positions`/`attn_mask` inputs to "albert_bert_encoder" at all: the MIL-traced CustomAlbert
--     computes position ids (from a registered buffer, sliced dynamically) and the additive attention
--     mask (always all-zeros -- real usage is always a single, unpadded utterance, same convention
--     convert_kokoro_albert.py's own bespoke topology already established) IN-GRAPH now, not host-side.
--   - "albert_bert_encoder" returns TIME-MAJOR (T,512) (`flat[t*512+c]`, this file's own "row_major"
--     convention below) instead of kokoro_driver.lua's "d_en_flat" Layout-A convention (`flat[c*T+t]`) --
--     a deliberate choice in export_kokoro_mil.py's own AlbertBertEncoderWrapper to avoid returning a
--     bare `.transpose()` as a traced graph's own output (a live non-contiguous view read in PRE-permute
--     order by this project's raw contiguous-byte-copy GGUF/weight extraction -- the exact bug
--     export_vits_mil.py's own StatsWrapper already found and worked around for VITS's `stats` output).
--     `from_row_major` converts straight to the per-timestep rows DurationEncoder's own "x" construction
--     needs, actually SIMPLER than kokoro_driver.lua's own manual c*T+t indexing loop.
--   - "decoder_vocoder" replaces FOUR bespoke calls (decoder_core, sinegen, stft_forward, generator) with
--     ONE: it takes asr/F0_curve/N_curve/style/rand_ini/noise_in/wsum directly and returns the finished
--     WAVEFORM -- no host-side har (STFT mag/phase) assembly or Generator-input wiring needed at all,
--     only the SAME rand_ini/noise/wsum host-precomputation kokoro_driver.lua's own generator call
--     already required (F0Ntrain and everything upstream of the decoder is IDENTICAL to kokoro_driver.lua
--     -- still bespoke/LSTM-bound, unchanged).
--
-- Expects every topology pre-registered by the host from ONE GgufModel over kokoro_mil.gguf -- none
-- uses a KvCache. It used to take two, because this export was partial and the LSTM-bound half was
-- borrowed from the pre-MIL kokoro.gguf alongside; P4.0.7 traced those from the real checkpoint too
-- (the six BiLSTMs as RecurrentPhases, the CNN/AdaLayerNorms/duration head/resblock stacks/1x1
-- projections as ordinary phases), so the artifact is self-contained now.
--
-- inputs: input_ids (int array, CustomAlbert's own vocabulary, caller wraps with leading/trailing 0 per
-- real KModel.forward's own convention), ref_s (2*STYLE_DIM floats: [1..STYLE_DIM]=decoder style,
-- [STYLE_DIM+1..2*STYLE_DIM]=predictor style -- the GGUF declares STYLE_DIM as the `loom.style_dim`
-- hparam, which is how a host knows how long to make it), speed (float), seed (int, seeds
-- loom.seed_rng -- SineGen's rand_ini/noise draws are the only stochastic step in this whole pipeline,
-- SAME draw order as kokoro_driver.lua: uniform first then gaussian, against the ONE shared rng_
-- stream).
--
-- style_dim, d_model, hidden_per_dir, harmonic_num, upsample_scale, gen_istft_n_fft and gen_istft_hop
-- used to be inputs too. They are the STYLE_DIM/D_MODEL/HIDDEN_PER_DIR/HARMONIC_NUM/UPSAMPLE_SCALE/
-- GEN_ISTFT_N_FFT/GEN_ISTFT_HOP locals below now (P4.0.8's first follow-up): the first three are read
-- off the real TextEncoder/ProsodyPredictor, and the last four are the istftnet geometry the
-- decoder_vocoder graph itself was traced with -- which the export now cross-checks against
-- config.json rather than assuming.
--
-- Returns: the raw waveform (flat f32 array), same convention as kokoro_driver.lua's own return.
