#!/usr/bin/env python3
"""Generates two small "supertonic"-family GGUF fixtures for test_supertonic_vocab.cpp.

Deliberately NOT the real 65536-entry `unicode_indexer.json` -- that asset lives in a reference-only
checkout and is what the GATE test (gate/test_supertonic_text_vectorizer.cpp) already compares against,
character for character, using expected ids generated by the real Python `TextVectorizer`. What is
hermetic here is everything that surrounds the table: the id<->codepoint inverse, the vocabulary size
derived from the table, and the default-language KV. A synthetic printable-ASCII table makes each of
those checkable by hand arithmetic (id == ord(c) - 32) instead of by a recorded oracle.

Two files, because two of the three properties can only be shown by a table that has them:

  supertonic_vocab_test.gguf          injective, and carries an explicit non-default `default_lang`
                                      ("es"), so a test can tell "read from the file" apart from
                                      "hardcoded en".
  supertonic_vocab_noninjective.gguf  two codepoints deliberately sharing one id, and NO default_lang
                                      KV -- so the same file covers the "en" fallback and the
                                      detokenize refusal.

Requires: pip install gguf
"""
import sys
from pathlib import Path

import numpy as np
from gguf import GGUFWriter

TOPOLOGY_JSON = '{"version": 1, "nodes": []}'
TABLE_SIZE = 65536  # same BMP-sized flat array shape as the real asset
FIRST_CP, LAST_CP = 32, 126  # printable ASCII, so id == cp - 32


def _write(out_path: Path, table: list, default_lang: str | None) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    w = GGUFWriter(str(out_path), "loom-supertonic-vocab-fixture")
    w.add_string("loom.architecture", "supertonic_vocab_test")
    w.add_string("model.graph_topology", TOPOLOGY_JSON)

    w.add_tokenizer_model("supertonic")
    w.add_array("tokenizer.ggml.supertonic.codepoint_to_id", table)
    if default_lang is not None:
        w.add_string("tokenizer.ggml.supertonic.default_lang", default_lang)

    # GgufModel::load() sizes a backend buffer from the meta context's tensors; a GGUF with zero tensors
    # hits a ggml_backend edge case, so a placeholder nothing reads is included -- same convention as
    # every other vocab-only fixture here.
    w.add_tensor("test.placeholder", np.zeros(4, dtype=np.float32))

    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()


def main() -> None:
    args = sys.argv[1:]
    injective_path = Path(args[0]) if args else Path("supertonic_vocab_test.gguf")
    noninjective_path = (Path(args[1]) if len(args) > 1
                         else injective_path.with_name("supertonic_vocab_noninjective.gguf"))

    table = [-1] * TABLE_SIZE
    for cp in range(FIRST_CP, LAST_CP + 1):
        table[cp] = cp - FIRST_CP
    _write(injective_path, table, default_lang="es")

    # Same table, except 'B' is sent to 'A''s id. Nothing else changes, so a test that sees the refusal
    # knows the collision is what caused it.
    collided = list(table)
    collided[ord("B")] = collided[ord("A")]
    _write(noninjective_path, collided, default_lang=None)


if __name__ == "__main__":
    main()
